---
title: "Literature Review"
execute:
  echo: false
website:
  navbar: false
  sidebar: false
---

```{r}
#| column: screen-inset-right
library(DT)
library(readxl)
df <- read_excel("Literature.xlsx")
DT::datatable(df,
              editable='cell',
              filter='top',
              options=list(autoWidth=TRUE,
                           pageLength=50,
                           searchHighlight=TRUE,
                           autoFill=TRUE,
                           dom='Bfrtip',
                           buttons =c('selectAll','selectNone','copy','csv','excel','pdf','print'),
                           colReorder=TRUE,
                           scrollX=TRUE,
                           keys=TRUE,
                           fixedHeader=TRUE,
                           deferRender=TRUE,
                           scrollY=2000,
                           scrollCollapse=TRUE),extensions=c('AutoFill','Buttons','ColReorder','KeyTable','FixedHeader','Responsive','Scroller','SearchPanes','Select')
              )
```

## Shen-Haw Ju(2013)

This paper **developed a finite element method with the effect of soil--fluid--structure interaction to calculate bridge natural frequencies**. It **validated that the natural frequencies calculated using the proposed finite element method had acceptable accuracy**. The **frequency change due to the fluid effect is not obvious**, but the changes in natural frequency with the scour depth are more obvious when the scour depth is such that pile cap is exposed.

The trend of the frequency decreases with the increase of the scour depth.

[Prendergast et al.](https://www.semanticscholar.org/paper/fd33fdebe7255c5df8ed94414b4415369ed5dc1f) critique this paper, **Ju**, by saying:

> Due to the difficulty in quantifying water-added mass and the numerical complexity involved (Ju, 2013), its effect on the natural frequency of vibration has been ignored in the present study.

[Bao et al.](https://www.semanticscholar.org/paper/5453c61955b66d109aac069ac56fafaf463ffb7a) said:

> The water was not included in this model as the effect of water on the PNF is possibly negligible according to the existing studies \[12,17\].

[Zhang et al.](https://www.semanticscholar.org/paper/ef2946bc911a0d88b16aa74c779a80ac07f41a64) said:

> This numerical model ignores the effect of soil mass and fluid-structure interaction which has been proved to have negligible influence on the structural dynamic behavior (Prendergast et al. 2013), Ju 2013).

[Jung](https://www.semanticscholar.org/paper/be545fa221d014f5514f0c749b74e4c05cba0ba0) said:

> 그러 나 각 세굴 모사에 따른 응답 지배주파수 감소의 경향은 깊이에 따라 뚜렷하지 않을 수 있으나 세굴 전후로는 감 소가 큰 것으로 확인되었다(Ju, 2013; Prendergast, 2015).

[Shang et al.](https://www.semanticscholar.org/paper/9d9f235e7a240adf5999f878d1208db319877116) said:

> ...the seismic response of the site, structure, and soil-pile-structure interaction, including the finite-element and finite-difference methods (Ju 2013), the dynamic p-y methods (Boulanger et al. 1999; Castelli and Maugeri 2009; Brandenberg et al. 2005), and the simplified two-step methods...

[Scozzese et al.](https://www.semanticscholar.org/paper/becc666b54542d5e5152da05488b011753ed3fcf) said:

> the studies of \[11,12\] in the context of masonry arch bridges, or the ones of \[13,14\] for steel and reinforced concrete bridges).

[Prendergast et al.](https://www.semanticscholar.org/paper/dad1be55f40f1bfbdc17087f7f3398b874464b2d) said:

> Several authors have investigated vibration-based scour detection methods, see Briaud et al. (2011); Elsaid & Seracino (2014); Foti & Sabia (2011); Prendergast et al. (2013); Prendergast et al. (2015); Klinga & Alipour (2015); Ju (2013); Chen et al. (2014).

[Choudhury et al.](https://www.semanticscholar.org/paper/ac04aa6ee17ce5b3d425c1e55e57376e73e77a3f) said:

> Analytical approaches based solely on numerical models have also been used to theoretically investigate the effects of scour on the dynamic properties of simply supported bridges, as seen in Ju \[41\], Zheng and Yu \[31\], Feng et al.

[Prendergast et al.](https://www.semanticscholar.org/paper/f5c4caa8218dbea8001fbf1f5507f3c0bdcf681d) said:

> Ju \[15\] conducted a study of the changes in natural frequency of a bridge due to scour incorporating soil--fluid--structure interaction, and concluded that the presence of water around foundation elements leads to lower natural frequency values than the absence of water due to wateradded mass effects.

## Prendergast(2015)

This paper investigates the **use of a vibration-based method to monitor scour** and the **effect of scour on the natural frequency of an offshore wind turbine**. It finds that **wind turbines founded in loose sand would exhibit the largest relative reductions in natural frequency resulting from scour**.

• Scour can reduce the ultimate capacity and alter the dynamic response of offshore wind turbine foundations.

• A vibration-based method can be used to monitor scour.

• Wind turbines founded in loose sand would experience the largest relative reductions in natural frequency due to scour.

The development of offshore wind energy converters is viewed as one of the most cost effective and politically acceptable short-term means of reducing society's reliance on fossil fuels. Since 1991, the majority (over 75%) of offshore wind turbines have been founded on large diameter steel tubular monopiles (EWEA, 2012) .

[Prendergast et al.](https://www.semanticscholar.org/paper/4fd835f5507c2465869c986a2298f4bbec3769a7) critique this paper, **Prendergast et al.**, by saying:

> The specific technical details of the model used in this paper have been published in Prendergast et al. (2016b); therefore, this section does not provide too much detail on the model.

[Alkhoury et al.](https://www.semanticscholar.org/paper/7a4c6a4ac61695710a7c70cada1c05de95bd56c6) said:

> Another approach was used by Prendergast et al.13 to derive the spring stiffness distribution in sand from p − y curves based on cone penetration test (CPT) data making use of the expression proposed by Suryasentana and Lehane.16 This expression is given as follows: p γ:z

[Jiang et al.](https://www.semanticscholar.org/paper/76e5c78494a7a7231cb2f5abfcff96eed5026961) said:

> At present, most studies (Prendergast et al. 2015, Abhinav and Saha 2017, Li et al. 2018) focus on the dynamic properties of OWTs such as the scour-induced shifts in the natural frequencies, while limited study (Jia et al. 2017) focuses on the seismic responses of OWTs under scoured conditions.

[Prendergast et al.](https://www.semanticscholar.org/paper/f87bf7c08a597a4da6eb6d13db5e6e6021f9b77e) said:

> Moreover, Prendergast et 379 al.\[12,26\] derived soil stiffness profiles using Eq.

[Amar-Bouzid](https://www.semanticscholar.org/paper/bf60e8fb1011b05d991b26aef76c007dd4c1e71c) said:

> In the computation of eigenfrequency most authors (Yi et al. 2015 and Prendergast et al. 2015) simply replaced the soil with a medium having an infinite stiffness.

[Prendergast et al.](https://www.semanticscholar.org/paper/dad1be55f40f1bfbdc17087f7f3398b874464b2d) said:

> The method for deriving soil stiffness is available in L J Prendergast et al. (2015).

[Aissa et al.](https://www.semanticscholar.org/paper/aba30ccfc9c28b5366e5c5258a01b8bb4f023f63) said:

> In the computation eigenfrequency f1, most authors in the past tried to model this complex system according fundamentally to two ways (Jin-Hak et al. 2015 and Prendergast et al. 2015).

[Subbian](https://www.semanticscholar.org/paper/2f4a01cdb0b4f9374f13f06260fcdd97110ad8d1) said:

> 10 2.6 Excitation frequency range for offshore wind turbine (Prendergast et al, 2015 \[3\]) . . . . . . . . . 11 2.7 Maximum horizontal hydrodynamic load resulting in the foundation . . . . . . . . . . . . . . . .

[Prendergast et al.](https://www.semanticscholar.org/paper/b10d3686603c17f49fc3085f02c64d7867f117bf) said:

> The site has been the location for several full and pilot-scale foundation tests over the last number of years (Gavin et al., 2009; Gavin and Lehane, 2007; Igoe et al., 2011; Prendergast et al., 2015, 2013; Prendergast and Gavin, 2016).

## Zarafshan(2012)

This paper describes the development and testing of a new type of scour sensor that is based on measuring the fundamental frequency of vibration of a rod embedded in the riverbed. The sensor uses a single fiber-optic Bragg grating (FBG) sensor for transduction of the vibration frequency. The inverse relationship between the fundamental frequency and the length of the sensor rod is used for detection of the scour depth.

• A new and simple type of scour sensor has been developed, tested, and implemented in the field.

• The sensor uses a single fiber-optic Bragg grating (FBG) sensor for transduction of the vibration frequency.

• A computational approach has been developed based on the Winkler spring reaction soil model for automated calibration of the scour sensor during installation in the riverbed.

[Loh et al.](https://www.semanticscholar.org/paper/642e1699bf83dcf7400577539ca6bac500774e17) said:

> The procedure adopted is comparable to that by Zarafshan et al. (2012), except their algorithm has been designed for FBG sensors.

[Park et al.](https://www.semanticscholar.org/paper/264027ed64b6479832fdf3091e9e57b27f0d5550) said:

> In addition, the existing IoT sensor is a vibrationbased sensor, and it was difficult to measure displacement, which is a major indicator of the dynamic characteristics of a bridge, as it only collects acceleration and natural frequencies (Zarafshan et al., 2012).

[Malekjafarian et al.](https://www.semanticscholar.org/paper/ad0fd3ad835b79a0be8b6630ae062a541648f2e6) said:

> Remote monitoring systems are under increasing development, and often require the installation or operation of a device close to a foundation element to ascertain the time-varying scour condition (De Falco and Mele 2002; Hunt 2009; Yu 2009; Briaud et al. 2011; Zarafshan et al. 2012; Fisher et al. 2013; Prendergast and Gavin 2014; Kong et al. 2017).

[Boujia et al.](https://www.semanticscholar.org/paper/75d404578212631b3bb19426db07bb8a7c31709d) said:

> For this purpose, new monitoring techniques have being proposed including the sliding magnetic collar (Lu et al, 2008), time-domain reflectometry (Yankielum and Zabilansky, 1999; Yu and Yu, 2009), fiber optic (Lin et al., 2005; Zarafshan et al., 2012) and vibration based techniques (Foti and Sabia, 2011; Zarafshan et al.

[Su](https://www.semanticscholar.org/paper/ded430c77c2105c87aac63fd1639fe5ac7ec1cd8) said:

> ...conductivity devices: time domain reflectometry (TDR, Yu and Yu., 2009); tilt sensor (Washer, 2010), fiber optic/ fiber bragg grating (FBG, Zarafshan et al., 2012), buried accelerometers (Gendaszek et al., 2013); float-out device: remote sensor (Briaud et al., 2011), wireless tracer (Yang...

[Zanini et al.](https://www.semanticscholar.org/paper/e9fa6d0268448fa6e6225cc86c9bb6505f2b7e1f) said:

> 1999; Yu 2009; Yankielun & Zabilansky 1999), buried or driven rod systems (NCHRP 2009; De Falco & Mele 2002; Zarafshan et al. 2012; Fisher et al. 2013), sound-wave devices (Nassif et al.

[Ghorbani et al.](https://www.semanticscholar.org/paper/ee7710a12f2c16b51875d95d4c4a27360799c9fe) said:

> (1) A novel output-only physics model-based scour level quantification method was introduced.

[Palanisamy et al.](https://www.semanticscholar.org/paper/2e01f501f83cd18c7831111a2e9e398ca0b1b9be) said:

> ...depth measuring instruments such as single use devices (Briaud et al., 2011), Pulse or radar devices (Hussein, 2012), Fiber-Bragg grating (May et al., 2002), Buried rods (Zarafshan et al., 2012), sound wave devices (Anderson et al., 2007) and electrical conductivity devices (Anderson et al., 2007).

## Kariyawasam(2020)

This paper describes a centrifuge-testing programme to establish the **sensitivity of bridge natural frequency to scour**. It found that the **level of frequency sensitivity is high**, demonstrating the potential for using natural frequency as an indicator of both local and global scour of bridges.

• Tests found up to a 40% variation in natural frequency for 30% loss of embedment for a two-span integral bridge with 15 m spans.

• Shallow foundation models showed lower frequency sensitivity to scour than deep foundation models.

• Frequency sensitivity to "global scour" is slightly higher than the sensitivity to "local scour", for all foundation types.

Bridge scour refers to the removal of soil from around structural foundations located in a river or coastal region as a result of the erosive action of water [1] . 

Scour around a bridge foundation leads to a reduction in bridge stiffness and stability because of the loss of embedment, which can even lead to bridge failure. According to historical bridge failure surveys, more than 50% of bridge failures have primarily been the result of scour-related causes [2,3].

## Myungjae Lee(2020)

### Summary

This paper presents a **study on the dynamic behavior of bridge pier by impact load test**. It was found that the **stability of the pier can be determined using the second mode, and the direction of the scour can be determined using the third mode**.

• The surcharge load had the greatest effect on the pier's first mode of vibration.

• The second mode of vibration can be used to determine the stability of the pier.

• The third mode of vibration can be used to determine the direction of the scour.

[Harasti et al.](https://www.semanticscholar.org/paper/7458914735b6d36b73119acefcc2e020102f76fd) said:

> During the lifespan of the bridge crossing rivers, changes in the flow and sediment regime are anticipated, as well as consequent change in the variable action-imposed loads on the structure \[2\], or even complete undermining of the foundation soil \[3\], which can result in bridge failure or even collapse.

[Bedon et al.](https://www.semanticscholar.org/paper/e5c2e388a48c5fe17a9d600bcacb30784e07f261) said:

> Impact test methods are presented in \[9\] to assess the structural capacity of bridge piers, given that the stability of bridge substructures is closely related to safety problems.

## Zarafshan(2012)

This paper studies the **change in the natural frequencies of the NREL 5MW monopile-supported offshore wind turbine (OWT) due to scour**. It uses the **OpenFAST and SESAM software** to model the wind turbine and consider soil-structure interaction. It is shown that the **increase in scour depth around the foundation of the OWT leads to a decrease in natural frequencies**.

• The natural frequencies of the NREL 5MW monopile-supported offshore wind turbine (OWT) decrease with increasing scour depth around the foundation.

• Soil density and scour hole depth have a significant influence on the obtained natural frequencies.

• Accelerations were extracted at nine locations along the tower resulting from applied wind and wave loads.

A model of the wind turbine was developed using OpenFAST and SESAM software which considers aerodynamic and hydrodynamic loading with soil structure interaction

Accelerations are extracted at nine locations along the tower resulting from applied wind and wave loads. The first two system natural frequencies are estimated using frequency domain decomposition (FDD) applied to the acceleration time-histories for each scour depth and soil type.

## Dong-Hyawn Kim(2020)

Scour induced failure probability of support structure for a given wave height then can be found by integrating the multiplication of hazard and fragility.

The proposed approach can be used in determining wind farm location where scour is significant.

A risk assessment procedure for offshore wind turbine support structures induced by scour

## G. Park(2022)

Strong aero/hydrodynamic loads can degrade the dynamic characteristics of offshore wind turbines because they are installed on soft seabeds.

In practice, this LSTM model could be used to predict future natural frequencies using the dynamic response of the structure, which can be measured using actual sensors (accelerometers and strain gauges).

## Ryu(2020)

The displacement at the pile head satisfied the structural design requirements.

A simplified analysis technique capable of predicting the dynamic behavior of a tripod suction pile subjected to a horizontal load

## Dong-Joon Kim(2014)

This paper performed centrifuge load tests of a tripod bucket foundation preliminarily designed as a supporting system of wind turbines and compared the results to those obtained from a test of a monopod bucket foundation

The yield moment for the tripod foundation was half that of the monopod.

When the resultant moment of cyclic loading was smaller than the monotonic yield moment, negligible accumulated plastic deformation was observed for both one-way and two-way loading. However, when the resultant moment was higher than the monotonic yield moment, significant cumulated deformation resulted.

[Barari](https://www.semanticscholar.org/paper/d75b7e0b582ff11078df7b64e37f9ba70e2e84a1) said:

> As the behavior of soil elements/1g lab tests cannot be directly transferred to the earth systems \[22\], the calibration of the HSsmall model against element tests is adopted by means of well-documented centrifuge tests of monobucket configuration in sand \[23\].

[Zhu et al.](https://www.semanticscholar.org/paper/eec3364a231044034d8164bb7c7a827e362dc38b) said:

> This value of aspect ratio was mostly adopted in previous studies (e.g. Dyvik et al. 1993; Du et al. 2016; Kim et al. 2014) especially when the caisson was used a footing of a jacket structure, whilst caissons with low aspect ratio are also very common, typically more suited for mono-caisson...

[Shen et al.](https://www.semanticscholar.org/paper/2bea2b5c00dd1ee557d7d5d17305d3f1d0bc85d5) said:

> It is found in the centrifuge tests in Kim et al. (2014) that the responses in rotation angle is much smaller for the tripod bucket foundation compared to the monopod foundation with a reasonable CONTACT Kanmin Shen shenkanmin\@163.com Powerchina Huadong Engineering Co Ltd, Hangzhou, Zhejiang, China...

[Park](https://www.semanticscholar.org/paper/3fc4c487103d99a42d0f3e26679bd041fc25323d) said:

> Kim et al.(2014)이 원심모형실험을 수행한 석션기초의 직 경(D)과 길이(L), 두께(t)는 각각 15.5 m, 10.5 m, 0.04 m이다.

[Seo et al.](https://www.semanticscholar.org/paper/0fe7508e8a572919319916bbc47d22042ee1ac57) said:

> The centrifuge test was carried out at 68.7 g using K-water centrifuge in Korea, which has a radius of 8.5 m and an effective radius of 7.5 m.

[Shen et al.](https://www.semanticscholar.org/paper/8e7fe1f2ffb7257baf7bada981c1ef61cef84a7e) said:

> Similarly, a constant value of a was adopted in most existing numerical studies, e.g., a¼ 1 in Kim, Hung, and Oh (2014) and Hung and Kim (2014) and a¼ 0.65 in He et al. (2021).

[Choo et al.](https://www.semanticscholar.org/paper/66e840195f38bbf1b72b1ed34daef5546ab0aa70) said:

> Marine Georesources & Geotechnology, 34: 729--740 Copyright \# 2016 Taylor & Francis Group, LLC ISSN: 1064-119X print/1521-0618 online DOI: 10.1080/1064119X.2015.1080334 et al. 2012; Kwag et al. 2013; Kim et al. 2014; Shin et al. 2014).

[Wang et al.](https://www.semanticscholar.org/paper/99e7edfc7d716b59d53efc7de4c8878b7f3fb25a) said:

> Kim et al. (2014) performed centrifuge cyclic load tests on a tripod bucket foundation prototype and compared the results with those obtained from a test on a monopod bucket foundation, showing that the moment--rotation curve of the tripod was nearly bilinear, whereas that of the monopod showed a...

[Olalo et al.](https://www.semanticscholar.org/paper/b308d27f724ef56339d03f4a7ef05c05ab6e724b) said:

> The maximum shaking frequency of the equipment is 300 Hz (Kim et al., 2014b; Segismundo et al., 2014).

[Jeong et al.](https://www.semanticscholar.org/paper/7b9d44d351a0bf265f077462513f6bbbb4c0bbfc) said:

> These results are to those of previous studies on the cyclic behavior of the tripod foundation \[20,30\].

[Wang et al.](https://www.semanticscholar.org/paper/eeefb712b9548f133cad7fef985d5029c4d9400b) said:

> Similar observations were also made from the centrifuge tests that investigated the monotonic response of monopod and tripod in silt (Kim et al., 2014).

[Jeong et al.](https://www.semanticscholar.org/paper/f276cf2f9d28471e20d1b3575bd1450fd37fcef8) said:

> The pad-eye (which implies loading point) is at 2/3 of the length from the top lid, which is the optimal loading point resulting in a minimum displacement of the bucket foundation (Bang et al., 2006; Kim et al., 2015).

[Wu et al.](https://www.semanticscholar.org/paper/5161fb24a8c0418da9625b2e11eed7b6311102e7) said:

> As a novel type of foundation in beach-shallow sea, suction bucket foundation emerges in the need of exploration of boundary oil fields (Hung and Kim, 2014; Kim et al., 2014).

## Y. Jeong (2021)

From a series of cyclic loading tests, the cyclic responses of the tripod foundation were evaluated in terms of temporary/permanent displacements and cyclic stiffness. Funded by Korea Electric Power Research Institute (KEPRI)

Ccyclic responses of an offshore wind turbine with a tripod foundation installed on an actual site

The cyclic behaviors of the tripod were more affected by the load amplitude than the number of cycles.

Permanent rotation increased logarithmically with the number of cycles

A simple method to predict the displacement and change in the foundation stiffness of the actual wind turbine is proposed based on the results of the model tests.

[Jeong et al.](https://www.semanticscholar.org/paper/f276cf2f9d28471e20d1b3575bd1450fd37fcef8) said:

> ...density 70% Dry unit weight (kN/m3) 14.5 Fine contents (passing #200) 37% Plastic index NP Soil classification, USCS SM Note: Values were obtained from Kim et al. (2018) and Jeong et al. (2021) model pile has a non-dimensional stiffness ratio, which is larger than the rigid behavior criteria.

## Yun-Ho Seo(2020)

The stiffness of the suction bucket cap and strain dependency of the soil play a significant role in predicting natural frequency, suggesting that these two factors should be considered in finite element analysis for the accurate prediction of dynamic responses of an offshore wind conversion system.

Dynamic analysis of the strain and acceleration measured during operational conditions shows that strain is more robust than acceleration with regard to the characterization of the overall dynamics of an offshore wind conversion system because the natural frequency of an offshore wind turbine is very low.

It can be inferred that the measurement of strain is a more effective way to monitor the long-term evolution of dynamic characteristics.

The suggested integrated framework and measurement campaign are useful not only to avoid conservatism that may incur additional costs during load calculation and design phases but also to establish an intelligent operation and maintenance strategy with a novel sensing technique.

to investigate the dynamic characteristics of an offshore wind turbine with tripod suction buckets through finite element analysis and full scale experiments

The measurement of strain is a more effective way to monitor the long-term evolution of dynamic characteristics of an offshore wind conversion system.

[Ngo et al.](https://www.semanticscholar.org/paper/3f6e7145280317d1dddd11932e0de0a34fc4b223) said:

> Figure 4 shows the four stages of the installation process of the full-scale 3 MW-class OWTs, which was designed by Doosan Heavy Industries and Construction in Korea \[18\].

## Xuefei Wang(2017)

Force-controlled lateral static and cyclic tests were performed at a centrifuge acceleration of 50 g. Four soil conditions were considered in centrifuge tests with a combination of loose/dense and dry/saturated sand.

The lateral bearing capacity can be reached when the normalized lateral displacement reached 3%.

A simplified calculation method is used as the third method and checked with tests results.

[Qin et al.](https://www.semanticscholar.org/paper/14bc27f94cce4462284cecbc352e170da93c0d1d) said:

> Most of the related studies focused on the vertical bearing capacity (Lehane et al. 2012; Spagnoli et al. 2015; Barari et al. 2017), and few focused on the lateral bearing characteristics (Medina et al. 2015; Wang, Yang, and Zeng 2017; Du et al. 2018; Wang, Lei, et al. 2020).

[Wang et al.](https://www.semanticscholar.org/paper/71d1c41a09742ad07519d20fbbc4ba6b68c08635) said:

> In  recent  studies,  model  tests  (Villalobos  et  al.,  2010; Chen,2013;  Zhu  et  al.,  2013;  Foglia  et  al.,  2015; Wang  et al., 2017), or field tests (Houlsby et al., 2005) were used to explore  the  response  of  the  suction  caisson  under  cyclic loading in sand or clay.

## Y. Jeong(2020)

The centrifuge tests model the correct soil self-weight stress levels, installation process and drainage response but could only test on the order of 10000 cycles.

Beneficial effects from densification of sand and consolidation in the clay lead to stiffness increases -- the effect of these increases on the natural frequency of the offshore wind turbine needs to be considered in design.

The rate of accumulation in caisson rotation is observed to be the same from centrifuge and single gravity tests, while the initial rotation differs with stress level, drainage regime, loading magnitude, soil profile and installation method.

Application of this calculation approach to field conditions showed that the long-term rotation for one-way loading would be higher for a sand over clay seabed than for a sand seabed.

[Jeong et al.](https://www.semanticscholar.org/paper/f276cf2f9d28471e20d1b3575bd1450fd37fcef8) said:

> Furthermore, the specimen container was kept outside the testing chamber for two days (Jeong et al., 2020b).

## Nissrine Boujia(2019)

This paper investigates the \*\*effect of scour on the natural frequency responses of bridge piers\*\*. It develops a \*\*scour depth sensor\*\* and conducts extensive laboratory tests in both dry sand and a soft clayey soil. Finally, an equivalent cantilever model is proposed to correlate the variation of the frequency of the sensor to the scour depth.

• Extensive laboratory tests were conducted to investigate the effect of the geometry and material of the sensor, the effect of the embedded length and the effect of soil type on the natural frequency responses of bridge piers.

• A numerical 3D finite-element model was developed and compared against experimental data to evaluate the effect of immersed conditions on the sensor's response.

• An equivalent cantilever model was proposed to correlate the variation of the frequency of the sensor to the scour depth.

Scour is considered as the main cause of bridge damages [1] and accounts for nearly half of all bridge collapses in the USA [2]. In France, the collapses of the Wilson Bridge in Tours (1978) and the St Louis Bridge on Reunion Island (2007) serve as national examples of damages caused by scour [3].


## Prendergast(2013)

This paper examines the effect that **scour has on the frequency response of a driven pile foundation system**. It is clear that there is a **very clear reduction in the natural frequency of the pile as the severity of scour increases**.

• Vibration-based damage detection techniques can be used to detect scour around bridge foundations. 

• Scour has a clear effect on the natural frequency of a driven pile foundation system. 

• A method is proposed that would allow the estimation of scour depth for a given observed pile frequency.

it only dealt with a single pile, and further research is required to apply these concepts to full scale structures

Scour can be defined as the excavation and removal of material from the bed and banks of streams as a result of the erosive action of flowing water [1].

[Larrarte et al.](https://www.semanticscholar.org/paper/fe5a56c86b0b9e9a0342978be3efb52d96ed33c0) said:

> Thus, Prendergast et al. (2013) concludes that given the rigidity of bridge piers, the effect of fluid-structure interaction can be neglected.

[Bao et al.](https://www.semanticscholar.org/paper/4bcf6a6b38979eb5f5aad819cf2de3ca6602b791) said:

> As for the second type, as shown in Figure 2c, the BSCC from the field study in Prendergast et al.(22) is nonlinear.

[Rahimi et al.](https://www.semanticscholar.org/paper/9272770770773fb0143562a8b8b8a9ded81a73f4) said:

> Prendergast, Hester [31] and Bao, Liu [35] neglected the complex fluid–structure and fluid–soil interactions, and conducted experiments on a monopile without the effect of flowing water where the scour was artificially induced by removing soil from around the pile.

[Russell et al.](https://www.semanticscholar.org/paper/47a64246823da6e805342f8edc81ad5a5aba314a) said:

> …from the Blessington test centre has been used by a number of offshore researchers over the past 10 – 12 years: Gavin & O’Kelly (2007) Gavin & Lehane (2005), Igoe, Gavin & O’Kelly, (2011) Gavin and Tolooiyan (2011) and Prendergast et al. (2013) all producing a reliable sets of geotechnical data.

[Prendergast et al.](https://www.semanticscholar.org/paper/fd33fdebe7255c5df8ed94414b4415369ed5dc1f) said:

> Similar studies of this phenomenon are reported in (Dezi et al., 2012; Prendergast et al., 2013).

[Prendergast et al.](https://www.semanticscholar.org/paper/4fd835f5507c2465869c986a2298f4bbec3769a7) said:

> 115 Extended Model 116 The work described by Prendergast et al. (2013) was validated for the case of a stand-alone 117 pile foundation with forced vibration being imposed through the use of a modal hammer.

[Prendergast et al.](https://www.semanticscholar.org/paper/0f11257877c593787718c326f1cf0069b31afd40) said:

> Moreover, Prendergast et 379 al.[12,26] derived soil stiffness profiles using Eq.

[Prendergast et al.](https://www.semanticscholar.org/paper/f636ba039c037da3550dd77db224681cbdd676a8) said:

> [5] Prendergast LJ, Hester D, Gavin K, O’Sullivan JJ.


## Kitchen(2014)

 
Guidance on scour risk management is currently provided by the Manual on scour at bridges and other hydraulic structures (May et al, 2002).

 The new Manual, due in 2014, will also provide lessons learnt with case studies such as Lower Ashenbottom viaduct (2004), River Crane, Malahide viaduct and Cumbria (all 2009) and a summary of methods for the assessment of hydrodynamic forces.
 
[Majtan et al.](https://www.semanticscholar.org/paper/fd6d6417ded3d130b3992db7f7fc05dfcbbf94a6) critique this paper, **Kitchen et al.**, by saying:

> However, none of these guidance or design codes [10,14,15] focused on masonry arch bridges and no specific equations for calculating forces on this bridge form are available [16].

[Maroni et al.](https://www.semanticscholar.org/paper/246f1fd8e498e2c2808fa4466da494211b59483a) said:

> where n is the kinematic viscosity of water and v0(d) is the shear velocity at the threshold of movement.(1) The last two equations are considered deterministic; therefore, the model errors are added to the Colebrook– White equation alone: the correlated, evB, c (i.

[Dikanski et al.](https://www.semanticscholar.org/paper/8f0d328b440c09c8db870008aeefafd785f327cb) said:

> [20] is used; errors associated with these estimates are explored using the Conveyance Estimation System software Environment [10].

[Argyroudis et al.](https://www.semanticscholar.org/paper/29b53008075ae0d051c8e59e52035cceff346b9b) said:

> With regard to guidelines for the design and assessment of bridges under hydraulic actions, the ones by Kirby et al. (2015) and BD97/12 (2012) are available in the UK, whilst in the US relevant documents are provided by NCHRP (2010a,b), NCHRP (2011) and FHWA (2012a).

[Maroni et al.](https://www.semanticscholar.org/paper/67f1da87d614ea93457d4c2e9e7a17010ac73e71) said:

> Equation (2) expresses the failure probability implicitly chosen by transport agencies when they fix their thresholds (i.

[Roca et al.](https://www.semanticscholar.org/paper/9d3eda24365f8395fa07fb8f244f8a11b97d1bc9) said:

> Approaches to risk assessment for river channels are discussed by May et al (2002) and should form part of a clear approach to inform asset management.

[Kim et al.](https://www.semanticscholar.org/paper/4d28e2294c6fd7d73aa2194eabca2fdcbb333692) said:

> The study on scour in the downstream area of drop structures generated by complex flow characteristics was conducted by Schokiltsh [7], Veronese [8], Zimmerman and Maniak [9], Bormann and Julien [10], Fahlbusch [11], Hoffmans [12], Federal Highway Administration (FHWA) [13], and Construction Industry Research and Information Association (CIRIA) [14].

[Sasidharan et al.](https://www.semanticscholar.org/paper/6dbba696fee8da63b713ee1e5497bc2bf3e0278f) said:

> CIRIA initially produced the manual C742 on bridge scour (May et al., 2002) and updated it with a second edition (Bridge et al., 2017; Kirby et al., 2015) that made insightful suggestions for a scour risk management strategy, bridge scour protection designs and economic appraisals using…

[Maniatis et al.](https://www.semanticscholar.org/paper/857d845be734105e53c73cb500bf83810c3c405e) said:

> Comprehensive manuals for bridge scour assessment are available for the UK (Kirby et al., 2015) and other countries (e.g. Arneson et al., 2012; Coleman and Melville, 2001).

## Saeed(2017)

This paper introduces a simplified method to obtain the fundamental frequency of offshore wind turbines supported by monopile foundations. Soil-pile interaction is modeled based on Winkler approach and concept of beam on elastic foundation. A parametric study is carried out to investigate the effect of important parameters of foundation including pile slenderness ratio, pile aspect ratio and pile mass on the system natural frequency.

• A simplified method is introduced to obtain the fundamental frequency of offshore wind turbines supported by monopile foundations.

• The natural frequency of the system with rigid pile and flexible pile with small value of slenderness ratio is compared with a numerical FE model for a typical 2 MW wind turbine structure and shows excellent agreement.

• A parametric study is carried out to investigate the effect of important parameters of foundation including pile slenderness ratio, pile aspect ratio and pile mass on the system natural frequency.

[Futai et al.](https://www.semanticscholar.org/paper/5c69bc4f2564911ce9d2eddc4c8d0edd3ea237f1) critique this paper, **Darvishi-Alamouti et al.**, by saying:

> [42] method presented a linear trendline, but underestimated the measured values.

[Alamouti et al.](https://www.semanticscholar.org/paper/79032a29734712e2b776b7cdac57d8beb2bbc5ed) said:

> For this purpose, the simplified method developed by authors Darvishi Alamouti et al. (2017) is used.

[Wang](https://www.semanticscholar.org/paper/e300eb7dd6887a3a066871d0cacc27d1fc8f00c2) said:

> The shear force F and bending moment M hereby can be written with a stiffness matrix as the following (Darvishi-Alamouti et al., 2017):

[Wang et al.](https://www.semanticscholar.org/paper/5183654c36a56fb8b18664e04eff533e029a5312) said:

> …expressed as: zr ¼ aLm (1) where a is a coefficient depending on the pile embedded depth Lm and load eccentricity Le in sandy soil, as defined below (Darvishi-Alamouti, Bahaari, and Moradi 2017): a ¼ 3Lm þ 4Le 4Lm þ 6Le (2) (3) Referring to the study of Cu ellar (2011), two geometric models (Mode…

[Ma et al.](https://www.semanticscholar.org/paper/052cc3e1e465cd119e9750c7a2f5b2cc555da749) said:

> Modal analysis is also an important means of interpreting dynamic responses [18].

[Mohamedien et al.](https://www.semanticscholar.org/paper/f7a961b2b603d2a5a67c519e7f7181f7f2b0a7c2) said:

> In the same way, the exact shape functions and there first order derivatives of the bending about z rotations and displacements can be performed by solving the two equations (13) and (14) as:

[Alamouti et al.](https://www.semanticscholar.org/paper/15e49f340ba89301e88e0f53a6240dd0abcc81aa) said:

> linearly varying modulus of subgrade reaction with depth [33,34]:

[Robinson et al.](https://www.semanticscholar.org/paper/ef5c5cc6a0fc9f694f2508a043cd3effbab25fcb) said:

> Darvishi-Alamouti et al. (2017) have modeled the soil-pile interaction based on Winkler approach and concept of beam on elastic foundation.

## Arany(2015)

This paper presents an analytical model of offshore wind turbines (OWTs) supported on flexible foundation. The model uses a **Timoshenko beam model** and **three springs** to predict the natural frequency of the OWTs. The results show that the model predicts the natural frequency of existing turbines with reasonable accuracy.

• The Timoshenko beam model does not improve the results significantly and the slender beam assumption may be sufficient. 

• The cross-coupling spring term has a significant effect on the natural frequency and needs to be included in the analysis. 

• The model predicts the natural frequency of existing turbines with reasonable accuracy.

 OWTs must be designed to avoid the frequency range of the forcing (wind turbulence and water wave spectra) and also the rotational frequency (1P) and the blade passing frequency (3P for a three-bladed turbine) ranges of the turbine. The importance of dynamics for offshore wind turbines is well established in the literature ( [1]- [5])
 
[Another paper](https://www.semanticscholar.org/paper/3a89e231dbdcfa18d599ddcdae6c308e1f9cc4c0) said:

> Differences between the designed natural frequency and that measured have been reported in the literature (Arany et al., 2015 and Kallehave et al., 2015). A decrease of the natural frequency after a few months has also been reported in Arany et al. (2015). There are various methods available to calculate the behaviour of a laterally loaded pile but little attention has been paid to multidirectional loading effects.

[Arany et al.](https://www.semanticscholar.org/paper/e84d1a2455978643aab304893532cd8e552672c3) said:

> The natural frequency of the system shown in Figure 8 can be estimated following Arany et al. (2015b); Arany et al. (2016). This simplified methodology builds on the simple cantilever beam formula to estimate the natural frequency of the tower, and then applies modifying coefficients to take into account the flexibility of the foundation and the substructure.

[Lovera](https://www.semanticscholar.org/paper/246d3846841f91be52e883453d55277734f31789) said:

> was studied in Arany et al. (2015) and Schafhirt et al. (2016). Arany et al. (2015) carried out a sensitivity study on the change of foundation stiffness on the first natural frequency of OWT founded on monopiles.

[Chowdhury et al.](https://www.semanticscholar.org/paper/a3f026a6c336691d1e75b60b0918b6ad7a54ddc4) said:

> Arany et al. (2015) did an extensive study on effect of Euler– Bernoulli beams vis-à-vis Timoshenko beam (i.e. considering shear deformation) on dynamic response of wind driven turbine shafts, while Chowdhury et al. (2013a) studied the effect of shear deformation on concrete gravity dam under…

[Nabiyan et al.](https://www.semanticscholar.org/paper/90617a7eb37e9497e53fbb86cd1ecdc10ce63108) said:

> m, which is a reasonable estimate for this monopile OWT as reported by Arany et al.(35) The translational DOFs are fixed at the base since the foundation stiffness in the lateral and vertical directions are significantly larger than the tower stiffness.

[Amar-Bouzid](https://www.semanticscholar.org/paper/bf60e8fb1011b05d991b26aef76c007dd4c1e71c) said:

> 13 on the basis of the formulae developed by Poulos and Davis (1980), Randolph (1981) and Carter and Kulhawy (1992), Arany et al. (2016) determined the values of the monopile stiffness coefficients which are added to the Table 4 for comparison.

[Bouzid et al.](https://www.semanticscholar.org/paper/2e87045d8c825e161ecbe0856f94516458d4e6b5) said:

> Furthermore, in order to improve the first natural frequency equation, Arany et al. (2014, 2015) derived expressions of natural frequency of OWTs on three-spring flexible foundations by means of two beam models: Bernoulli-Euler and Timoshenko.

[Jalbi et al.](https://www.semanticscholar.org/paper/cfa68f66430037111a06fed602032927fb00824a) said:

> Simplified numerical methods to predict the natural frequency (including soil structure) interaction have been developed by the University of Surrey research group such as the work by Arany, et al. (2016) and Arany, et al.

## Dong Xiaofeng(2018)

This paper discusses the **structural vibration characteristics and operational modal analysis of offshore wind turbine**. It finds that the **integral operational modal identification method of offshore wind turbine in the range of full power** is the most effective.

• Structural vibration displacement signals of a Chinese offshore wind power prototype were obtained to analyze the vibration response characteristics and operational modal analysis of the measured structure.

• An integral operational modal identification method of offshore wind turbine in the range of full power was proposed based on traditional and modified stochastic subspace identification technologies. 

• The modal identification results and the relationship between structural modal parameters and environmental/operational factors were illustrated.


[Barber et al.](https://www.semanticscholar.org/paper/58a3be52ef0266f36e67579f2edcf47f2137d471) critique this paper, **Xiaofeng et al.**, by saying:

> The identification results could be improved via a modified stochastic subspace system identification, for instance, as proposed by Dong et al. (2018), or via direct measurements on the blades (instead of on the tower and nacelle only) (Tcherniak and Larsen, 2013), especially to improve the…

[Cevasco et al.](https://www.semanticscholar.org/paper/861b9134487a554fd72134076ff1a6d60bfb45d4) said:

> Further challenges for the field application of the detection algorithms will come from the statistical uncertainty of the measured data, associated with the OMA and the violation of the method’s assumptions for the extraction of modal parameters [17,18,52].

[Cui et al.](https://www.semanticscholar.org/paper/0b534035b843f933931d6e6ddbab4e48164d8ad0) said:

> The constant accumulation of damage inevitably affects the normal operation of the structure and can even lead to destruction and failure of structural integrity.1 Therefore, in the routine operation of a structure, structural health monitoring (SHM) must be conducted to discover any potential damage existing in the structure in a timely manner and perform targeted repair and maintenance to guarantee normal operations and minimize the occurrence of major accidents.1,2 The damage identification method based on structure vibration information has the advantages of convenient detection and high precision and is widely used in the field of SHM.3 However, structural strain information is more sensitive to structure damage than displacement information.4 Studies have used strain sensors to collect structural vibration signals to analyse structural health.

[Chen et al.](https://www.semanticscholar.org/paper/42c231499f454e64117d2c92c38acb0bf350fa9a) said:

> The time integration algorithm used to solve the equation of motions in Equation (1) in the time domain is HHT-α [20] – a generalised version of the widely-used Newmark-β

[Li et al.](https://www.semanticscholar.org/paper/8cc1ba01e38785c435f5cc07e6fdd4948841abe3) said:

> Therefore, the current modal parameter identification method for OWTs is based on accelerations (Dong et al., 2018).

[Laaouidi et al.](https://www.semanticscholar.org/paper/ee882bf4bd2d222968619ecc61b730c6c85d6a07) said:

> For example, a study was conducted by Dong et al. (2018) on structural vibration monitoring and operational modal analysis of the structure of offshore wind turbines.

[Qin et al.](https://www.semanticscholar.org/paper/66d6471c72b945479f08773db450b96eca7a2bd8) said:

> Frequency is an important characterization parameter for damage identification, health monitoring, and finite element analysis [1,5].

[Oh et al.](https://www.semanticscholar.org/paper/b26fc346a4224dea9fc6329d04d73c36e021d8d1) said:

> Stochastic Subspace Identification (SSI) has been applied to the operating offshore wind turbine with Jacket and tri-pod foundation (Haeckell and Rolfes (2013) 6 ) and suction bucket foundation (Dong et al. (2018) 7 ), as well as the onshore wind turbine (Oliveira et al. (2018) 8 ).

[Yu et al.](https://www.semanticscholar.org/paper/e3e657bc4cc414e52815bb8aab2050d8ab9d5cfa) said:

> Gomez, Gur, and Dolan (2013) established a performance evaluation of single-pile offshore wind turbine structures based on modal analysis as well as system identification for FM of vibration frequency of offshore wind turbine towers.

## Adhikari(2011)

This paper outlines a **simplified approach for free vibration analysis of wind turbine structures**, taking the **soil-structure interaction into account**. A closed-form approximate expression has been derived for the first natural frequency of the system, which has been validated using an exact numerical method, laboratory based experimental measurement and field measurement of a real wind turbine structure.

• A closed-form approximate expression has been derived for the first natural frequency of a wind turbine structure taking the soil-structure interaction into account. 

• The proposed expression is a function of geometric and elastic properties of the wind turbine tower and properties of the foundation including soil. 

• The proposed expression has been independently validated using an exact numerical method, laboratory based experimental measurement and field measurement of a real wind turbine structure.


[Aissa et al.](https://www.semanticscholar.org/paper/aba30ccfc9c28b5366e5c5258a01b8bb4f023f63) critique this paper, **Adhikari et al.**, by saying:

> Since the analysis of the whole system composed of tower/ monopile/soil is cumbersome and the dynamic analysis is hard to perform, other researchers (Adhikari and Bhattacharya 2011 and Zaaijer 2006 among others) proposed different concepts in which the tower and the subsoil/monopile system can be…

[Rezaei](https://www.semanticscholar.org/paper/be29c1aca75ae21e0660f663be91e279d5892047) said:

> Adhikari and Bhattacharya (2011) suggest that the issue concerning offshore monopiles is the dependence of their design on empirical data regarding stiffness degradation of soil under cyclic loading and emphasised that relying on the recommended pile design methods does not take this into…

[Arany et al.](https://www.semanticscholar.org/paper/e84d1a2455978643aab304893532cd8e552672c3) said:

> Further details on the analysis required can be found in Adhikari and Bhattacharya (2011); Adhikari and Bhattacharya (2012); Arany et al.

[Buckley et al.](https://www.semanticscholar.org/paper/735db9c3325b5af1d09c1fec3f8edea61d918852) said:

> This method, proposed by Adhikari & 295 Bhattacharya [19], has been well documented and validated by experiments, giving reasonably 296 high degree of confidence in the method used.

[Yang et al.](https://www.semanticscholar.org/paper/9ae5725e004e23d0dcfc70382da0fc389d547cc2) said:

> (3), which is 0.56 Hz, and Adhikari’s method (Adhikari and Bhattacharya, 2011) result of 0.7407 Hz, the proposed method provides a much more accurate solution for the system fundamental frequency.

[Koç et al.](https://www.semanticscholar.org/paper/ee2a50483cf5bd8eb2ef9c3954e93eb9013b869d) said:

> This certainly affects the performance of wind farm (Adhikari and Bhattacharya 2011).

[Gupta](https://www.semanticscholar.org/paper/4edbe085d1b2b091882dfff1710c075960fc3e58) said:

> 8 approximate (Adhikari and Bhattacharya 2011) and exact (Adhikari and Bhattacharya 2012) equations using which an assessment of the natural frequency of an OWT-foundation system can be made.

[Bhattacharya et al.](https://www.semanticscholar.org/paper/0974e6fe6ab46044e857b553c6ea82277a219938) said:

> More details on the dynamics of monopile supported wind turbines are given in Lombardi (2010), Adhikari and Bhattacharya (2011, 2012), Bhattacharya and Adhikari (2011) and Bhattacharya et al (2012).

[Bhattacharya et al.](https://www.semanticscholar.org/paper/ef4077f2fb174b1947f80ac6d182fe250b06dcf5) said:

> In this context, readers are referred to the work of Adhikari and Bhattacharya [23,27] on the non-dimensionalization of the Euler–Bernoulli equation considering the flexibility of the foundation.

## Aissa(2018)

This paper uses the **semi-analytical finite element analysis** to study **monopiles for offshore wind turbines**. It finds that **lateral stiffness KL, rotational stiffness KR and cross coupling stiffness KLR for both rough and smooth interfaces depend only on the value of the monopile slenderness Lp/Dp**.

• An extensive parametric study was conducted to develop functional forms of design equations for large diameter monopiles used for supporting offshore wind turbines. 

• Lateral stiffness KL, rotational stiffness KR and cross coupling stiffness KLR for both rough and smooth interfaces depend only on the value of the monopile slenderness Lp/Dp. 

• Analytical expressions have been incorporated into the expressions of the Offshore Wind Turbine (OWT) natural frequency of two wind farm sites, with excellent agreement between the computed and the measured natural frequencies.

 It has been found that lateral stiffness KL, rotational stiffness KR and cross coupling stiffness KLR for both rough and smooth interfaces depend only on the value of the monopile slenderness Lp/Dp rather than the relative soil/monopile rigidity Ep/Es usually found in the offshore platforms designing codes (DNV code for example).

[Bhattacharya et al.](https://www.semanticscholar.org/paper/1aa6721aef7fbaf46ec90fcf67130c01f191a426) said:

> For further discussion on these aspects, the readers are referred to [10, 13, 14].

[Mohammed](https://www.semanticscholar.org/paper/8256209a53df44b5141f339047c09a2cc51f94a9) said:

> The displacement can be expressed in the form of Fourier series: are the amplitudes of displacements that are symmetric with respect to the ( ) plane and  are the amplitudes of displacement that are antisymmetric with respect to the ( ) plane, is harmonic number, and is the total number of harmonic terms considered in the series.

[Medjitna et al.](https://www.semanticscholar.org/paper/075c401b30e4dc2c4d66623c8058a276647f30ab) said:

> Indeed, Amar Bouzid (2011) studied a piled footing by carrying out a parametric study in which he analysed the influence of the interface characteristics on the displacement and bending moment profiles. In the context of laterally loaded piles, Amar Bouzid, Bhattacharya, and Dash (2013) used the FSAFEM to derive scaling coefficients allowing to obtain any p–y curve from its laboratory calibrated τ–γ curve using an approach called mobilised strength design concept.

[Ahlinhan et al.](https://www.semanticscholar.org/paper/06c1f270452e41218201de41adf803297075e551) said:

> Reference can be made to Aissa et al. (2018) [2], and Kallehave et al. (2015) [3] for the applicability of each foundation structure in the function of the sitespecific conditions.

[Amar-Bouzid](https://www.semanticscholar.org/paper/bf60e8fb1011b05d991b26aef76c007dd4c1e71c) said:

> This type of foundation known as monopile foundation, is a large diameter (3 to 6 m) hollow open ended steel pile with length-todiameter ratio usually less than 10 (Achmus et al. 2009; Aissa et al. 2016; Arany et al. 2015 and Damgaard et al. 2014).

## Varghese(2022)

This paper presents a compendium of mathematical expressions to compute the **natural frequencies of offshore wind turbine structures**.

• This paper presents a compendium of mathematical expressions to compute the natural frequencies of offshore wind turbine (OWT) structures on various foundation types. 

• The calculations presented can be easily made using spreadsheets.

• Example calculations are provided to compare the compiled solutions against publicly available sources.

Typically costing 16-34% of the total cost of a wind farm project, the foundation system becomes a controlling factor [1]. The choice of a foundation in turn depends on factors such as the water depth, fabrication, installation, operation and maintenance, decommissioning, and economics

## Bhatacharya(2011)

This paper investigates the **future performance of offshore wind turbines**. It suggests that the best way to predict this performance is through **small-scale laboratory experimental investigation**. The paper provides **scaling laws** for the design of such model tests.

• Scaling laws are derived for the design of small-scale laboratory experiments to study the long-term performance of offshore wind turbines.

• Non-dimensional groups that need to be preserved while carrying out these tests are identified. 

• The effectiveness of the chosen non-dimensional groups is investigated through controlled tests.


[Klinkvort](https://www.semanticscholar.org/paper/9b21a96ea903b4dcf66d668c2588959b23abedc2) critiques this paper, **Bhattacharya et al.**, by saying:

> This requires some initial knowledge to the problem which can be found in e.g. Reese and Impe (2001), Randolph (2003) or Bhattacharya et al. (2011).

[Pakrashi et al.](https://www.semanticscholar.org/paper/3286337365fdd6c324ffc10807559997cf48e7ab) said:

> system (Bhattacharya et al., 2011; Bilello et al., 2004), uncertainties in developed models and testing protocols for models (Adhikari et al.

[O’Kelly](https://www.semanticscholar.org/paper/057ada6b4e25d08d7e94e5299f064d8515bbc9a5) said:

> However, the satisfaction of such scaling conditions for similarity in granular soils is not trivial (Bhattacharya et al., 2011; Dong et al., 2001), especially for a complex problem such as OWTs where one has dynamics, aerodynamics, soil– structure interaction and fluid flow around the foundations.

[Nikitas et al.](https://www.semanticscholar.org/paper/2aa9f44db43c2fd7dedb54d9be8819f7a28dce82) said:

> Further details of the testing procedure, soil container requirements, similitude/scaling relations can be found in Bhattacharya et al (2011).

[Arshad et al.](https://www.semanticscholar.org/paper/a63f779177b2117f945fc4b58d3325492e687df8) said:

> However, the satisfaction of such scaling conditions for similarity in granular soils is not trivial (Dong et al. 2001, Bhattacharya et al. 2011).

[Hanssen et al.](https://www.semanticscholar.org/paper/09f607d0cc8fbcbdd29e303025e01083a788c61c) said:

> If the presented results are to be used at proto-type scale, scaling laws as suggested by Bhattacharya et al. (2011), Iai (1989) and Iai et al.

[Patra et al.](https://www.semanticscholar.org/paper/29a5aa1bd6dec17e769049e6667a82dc62dca3b9) said:

> Offshore wind turbines are designed as soft-stiff approach, where the fundamental frequency of soil-monopile-tower system is placed between the rotor frequency (1P) and blade passing frequency (3P for 3 bladed turbines) (Cui and Bhattacharya 2016, Bhattacharya et al. 2013). The resonance condition is avoided for an OWT structure keeping the fundamental frequency of the system ±10% away from the rotor frequency (1P) and blade passing frequency (3P) (DNV GL-ST-0126 2016). Past studies by Lombardi (2010), Bhattacharya et al.

[Gupta](https://www.semanticscholar.org/paper/4edbe085d1b2b091882dfff1710c075960fc3e58) said:

> …Figure 1.2: Forcing frequencies of a Vestas V90 3 MW OWT (Regenerated from Bhattacharya et al. 2011)…

[Bhattacharya et al.](https://www.semanticscholar.org/paper/0974e6fe6ab46044e857b553c6ea82277a219938) said:

> The aspect ratio of the caisson (diameter to depth ratio) should also be maintained to ensure the pore water flow is reproduced, details can be found in Bhattacharya et al (2011).

## Mostafa(2019)

This paper **develops a new semi analytical formulation** which **models the dynamic behavior of offshore wind turbine with variable cross section and flexible foundation**. The **wind turbine tower is modeled using Euler-Bernoulli beam model while the soil-tower interaction is modeled by rotational and lateral springs at the lower end of the tower**. The **predicted natural frequencies of the current proposed mathematical technique were validated and compared with those of two other analytical and experimental techniques, for four selected offshore wind turbines**, and results were found to be in very good agreement.

• A semi-analytical formulation was developed to model the dynamic behavior of offshore wind turbines with variable cross section and flexible foundation. 

• Recursive differential method was used to calculate natural frequencies which was found to be efficient in terms of accuracy and computational cost.

• The results of the current model were found to be in better agreement with the experimental results compared to those of the constant cross-section approximation.

## Mouafo Robinson(2021)

This paper uses the power series method to accurately predict the natural frequencies of eleven offshore wind turbines. It is found that the previous researches, which the whole wind turbine was taken as a single beam, with a tower being tapered and its wall thickness being negligible compared to its diameter, is only accurate for OWT with tower wall thickness lower than 15 mm.

• The power series method (PSM) was used to accurately predict the natural frequencies of eleven offshore wind turbines (OWT).

• Case 3, which describes the tower as a tapered beam with varying thickness along its height, produced the most accurate results with a relative error of up to 0.01%.

• The tower-to-pile thickness ratio is an important design parameter that must be taken into account during the design.

## Xuguang Chen(2017)

This paper investigates the **effect of scour on the stability of a suction bucket foundation**. It is revealed that the **behavior of the foundation bearing capacity can be divided into two stages: the initial cyclic stage and the final stage (showing either cyclic stability or cyclic failure)**. With the increase in scour depth, the stability of foundation is gradually reduced, the behavior of foundation gradually changes from a state of cyclic stability to cyclic failure, and the number of waves that can be withstood is drastically reduced.

• The behavior of the suction bucket foundation bearing capacity can be divided into two stages: the initial cyclic stage and the final stage (showing either cyclic stability or cyclic failure). 

• With the increase in scour depth, the stability of the foundation is gradually reduced, and the number of waves that can be withstood is drastically reduced.

• The height of the center of rotation of the suction bucket was observed to descend with the increase in scour depth.

[Liu et al.](https://www.semanticscholar.org/paper/acb9766de5dd243db6c2050b4ea9d14c40472f5d) said:

> Based on the model test implemented in a flow-wave flume, Chen et al. (2017) analyzed the stability of a suction caisson under wave cyclic loading and scour.

[Liu et al.](https://www.semanticscholar.org/paper/d09b95344b00ad6cc80632630b6f7301c2945627) said:

> The maximum horizontal displacement of the upper part and the lower part of the bucket grows with working loads, which shows a tendency to accelerate [28,29].

## Sungho Park(2017)

This paper investigates the **effects of stick-up height and water depth on scouring around a suction bucket foundation** for a fixed offshore wind turbine. It uses the **open source libraries OpenFOAM** to simulate a violent flow around a foundation. The results show that **a larger scouring region is observed with an increase in the stick-up height** and that **the water depth has an insignificant effect on the scouring**.

• A parametric study of the various sub-structures of a fixed offshore wind turbine was performed to investigate their effects on the scouring phenomena.

• An increase in the stick-up height of a suction bucket foundation resulted in a larger scouring region due to the down-wash flow around the foundation.

• The water depth of a monopile had an insignificant effect on the scouring.

[Song et al.](https://www.semanticscholar.org/paper/be790d8c95dee6390e20cd74e0a002f73c5e49ec) said:

> 이러한 상호작용은 Park et al.(2017)에서는 예측하기 힘든 부분이다.

[Dang et al.](https://www.semanticscholar.org/paper/80501e1eb3b7d1f834d4d34c4ae5352bac046960) said:

> …for spatial discretization and solves Reynolds averaged Navier-Stokes (RANS) equations for incompressible flows by using a PIMPLE algorithm (a mixture of the pressure implicit with splitting of operators (PISO) and semi-implicit method for pressure linked equations (SIMPLE)) (Park et al., 2017).

[Song et al.](https://www.semanticscholar.org/paper/6605357aa9b3271170622f82ebd15c267b0689e2) said:

> In the rigid seabed approaches, scour was predicted by the shear stress magnitude at the seabed boundary [10,11].


## YoungJin Kim(2021)

The scour risk assessment was conducted for ultimate limit state of newly developed penta pod suction bucket support structures for a 5.5 MW offshore wind turbine. The hazard was found by using an empirical formula for scour depth suitable for considering marine environmental conditions such as significant wave height, significant wave period, and current velocity. The scour fragility curve was calculated by using allowable bearing capacity criteria of suction foundation. The scour risk was assessed by combining the scour hazard and the scour fragility.

This paper assesses the **scour risk of penta pod suction bucket support structures for offshore wind turbines**. It finds that the scour risk is **low**.

• An empirical formula was used to calculate the scour depth for the penta pod suction bucket support structures. 

• The scour fragility curve was calculated using allowable bearing capacity criteria of suction foundation. 

• The scour risk was assessed by combining the scour hazard and the scour fragility.

해상풍력터빈 지지구조물 중 석션버켓 지지구조물은 파일 을 항타하여 설치하는 다른 지지구조물보다 공사기간이 짧고, 경제적으로 설치가 가능하다 (Oh et al., 2012). 이러한 석션 버켓 지지구조물의 주요 설계인자는 수평 허용 지지력과 기 초의 강성이다. Latini and Zania(2017)는 석션버켓의 동적거 동을 조사하여, 석션버켓의 스커트 길이가 동적 거동을 결정 하는 중요한 매개변수라고 밝혔고, 수평 하중 지지력은 버킷 직경과 길이의 비의 영향을 크게 받으며, 초기 강성은 모래 의 상대적 밀도와 버켓의 기하학적 구조에 크게 좌우되는 것 으로 일련의 연구를 통해 조사되었다 (Achmus et. al., 2013;Ding et al., 2015;Thieken et al., 2014). 석션버켓 지지구 조물을 토질층이 깊지 않은 지역에 설치할 경우, 지지력을 발 휘하기 위하여 직경이 비정상으로 커져야 하는 문제점이 있 다. 이러한 문제점을 해결하기 위하여 펜타팟 셕선버켓 지지 구조물을 개발하였으며 (Ngo et al., 2020) A :

## Shu Zhu(2021)

This paper investigates the **influence of scour depth, stress history, and aspect ratio on the vertical bearing capacity of suction caissons**. It finds that **the capacity decreases with increasing scour depth, and its scour sensitivity is lower compared with the pull-out response**. The greater the aspect ratio, the greater the scour effect on the capacity.

• The capacity of suction caissons decreases with increasing scour depth, and its scour sensitivity is lower compared with the pull-out response. 

• The capacity after scour is larger when the stress history is considered, so ignoring the stress history leads to a conservative design. 

• The greater the aspect ratio, the greater the scour effect on the capacity.

## Rezaei(2018)

This paper investigates the **effects of scour on offshore wind turbines**. It finds that **scour can lead to a significant reduction in fatigue life**, but this can be recovered by **backfilling the scour hole**.

• Scour can significantly reduce the fatigue life of operational monopile-supported offshore wind turbines.

• Backfilling the scour hole can recover the fatigue life, depending mostly on the depth after backfilling. 

• An approximate fatigue analysis method is proposed, based on the full time-domain analysis for 1 scour depth, predicting with good accuracy the fatigue life for different scour depths from the quasi-static changes in the bending moment.

[Qi et al.](https://www.semanticscholar.org/paper/98ce03ee062ef15e7377521f30ff1ae7f3407970) said:

> [95] presented a study of scour and backfilling effects on the FL of a 5 MWmonopile supported OWT, using quasistatic, modal, and time-domain fatigue analyses.

[Chen et al.](https://www.semanticscholar.org/paper/42c231499f454e64117d2c92c38acb0bf350fa9a) said:

> For onshore wind turbines, the total damping is a closer approximation of the aerodynamic damping [10] as foundation damping is low.

## Jinzhong Liu(2017)

This paper investigates the **effects of scour on suction caisson**. It finds that **scour depth affects the ultimate moment capacity of suction caisson** and that **it is feasible to replace the ultimate moment capacity when both dilatancy and stress history are considered with that when only dilatancy is considered**.

• The parameters of shallow soil change considerably after scour, and the larger the scour depth, the greater is the change in the parameters. 

• The ultimate moment capacity of suction caisson is found to greatly reduce under scour.

• It is feasible to replace the ultimate moment capacity when both dilatancy and stress history are considered with that when only dilatancy is considered.

[Zhu et al.](https://www.semanticscholar.org/paper/d6fbf53b20944843a6ba6d042801b5b0421d826b) said:

> The diameter D includes seven cases, corresponding to seven aspect ratios, that is, g ¼ ½0:5, 0:64, 1, 2, 4, 6, 8 : Among them, the foundation size corresponding to g ¼ 0:64 is the same as that in Liu et al. (2019).

[Liu et al.](https://www.semanticscholar.org/paper/acb9766de5dd243db6c2050b4ea9d14c40472f5d) said:

> This change has been investigated and detailed in Lin et al. (2010, 2014b); in addition, a detailed procedure of iterative computation is presented in Liu et al. (2018).

## Xuguang Chen(2018)

This paper studied the **horizontal static loading of a suction bucket foundation in sand**. It found that the **ultimate bearing capacity of the foundation is influenced by the scouring depth, scouring width, and length-diameter ratio**.

• Obtained a variation law for the ultimate bearing capacity of the foundation considering three aspects: displacement change, soil pressure distribution, and turning point position

• Summarized the relationship between horizontal loads and displacements at different aspect ratios. 

• Demonstrated the influence of scouring factors on the distribution of soil pressure and the rotation point and revealed the mechanism influencing the scouring depth, scouring width, and history of stress on the horizontal bearing capacity of a suction bucket foundation.

[Zhu et al.](https://www.semanticscholar.org/paper/d6fbf53b20944843a6ba6d042801b5b0421d826b) said:

> Furthermore, Chen et al. (2019) based on the model test in a sand tank studied the effect of scour depth and scour hole shape on the lateral behaviors of suction caissons under static load.

## Felipe AV Jara(2006)

This paper investigates the **behaviour of suction caisson foundations in sand and in clay**. It is based on **experimental work carried out using model scaled caissons**. The **analysis of the results allowed the determination of parameters for hyperplasticity models**.

• Suction caissons exhibit higher bearing capacity than caissons installed by pushing in loose and dense sands.

• Moment capacity of suction caissons is very small under undrained conditions and low constant vertical loads.

• Negative excess pore pressures generated during suction installation reduce vertical displacements in clay in the short term.

[Haddad et al.](https://www.semanticscholar.org/paper/e59c4372fb6937a272c6975ed4e31f45c045c0c6) said:

> Most of the previous studies have been conducted to investigate the behavior of bucket foundations in medium to dense sands and there is limited research in loose sand (Villalobos (2006) and Eid et al. (2009)).

[Liu et al.](https://www.semanticscholar.org/paper/acb9766de5dd243db6c2050b4ea9d14c40472f5d) said:

> It should be noted that the value of Q is re-taken to 8 and the value of R is still taken as 1 based on the undrained triaxial tests for the Redhill 110 sand (Kelly, Houlsby, and Byrne 2006b; Villalobos 2006), which is different from the values in Lin et al.

[Liu et al.](https://www.semanticscholar.org/paper/db9beb4e5ea9de65924117c1acc64e4c2b45d542) said:

> 4 Verification by other researchers In order to further validate the calculation method, smallscale model tests performed by Villalobos et al. (2009) is Fig.

[Foglia et al.](https://www.semanticscholar.org/paper/121f91653598254a7aa66e6934a9f653ecff5f88) said:

> After scrupulous considerationand comparison with Villalobos (2006) a value oft0 = 0.007 was taken.

[Villalobos et al.](https://www.semanticscholar.org/paper/df821a418105f197a9954368e58e1ec5857811ea) said:

> A summary of all test results can be found in Villalobos (2006).

[Zhang et al.](https://www.semanticscholar.org/paper/3329b0a8a0be940fa88d4693673d73276eb391b7) said:

> Therefore, compared with the calculated MSC capacity by using methods proposed by Villalobos (2006) and Zhu et al. (2014) based on the rotation center position in the serviceability limit state, the calculated result based on the rotation center position in the ultimate limit state may be…

[Zafeirakos et al.](https://www.semanticscholar.org/paper/bd4ee4e4794657acc00e519578921b23e25176f5) said:

> The vertical load, N, to which the pure horizontal and pure moment capacities were determined corresponds to the vertical force (denoted as V in Villalobos [63]) that the caissons in the experiments were loaded after their installation in the sand (for the readers’ reference, the vertical load required for the caisson installation in Villalobos [63] is denoted as V0).

[Faizi et al.](https://www.semanticscholar.org/paper/b7e64ebe6894260fbcc596028595d6e95f1dcc8c) said:

> To define the yield point, the method described by Villalobos [32] was 270 used.

[Patra et al.](https://www.semanticscholar.org/paper/3a28c60f2a1924ae6fcec65bc07954a4a55bffc6) said:

> …turbine blade at the hub ðFbÞ and (b) load acting on the tower ðFDÞ: The load acting on the turbine blade, i.e., wind thrust on the hub ðFbÞ is given by Jara (2006) as follows: Fb ¼ 0:5qaPRT2U2CT2 kSð Þ (2) where RT is the radius of the rotor in m. qa is the density of the air at 150C and 1 atm…

[Bisoi et al.](https://www.semanticscholar.org/paper/6d566a740036e977bb30ba92e5ab786a7ff7a775) said:

> The 1P load acting at hub height (Fb) is estimated (Jara 2006) Fb ¼ 0:5qapR2TV 2 hubCT ksð Þ ð8Þ where Vhub is the wind speed at the hub height in m/s, RT is the rotor radius in m, qa is the air density which equals to 1.23 kg/m3 at 15°C at 1 atm, and CT(ks) is the thrust coefficient which is a…

[Lee et al.](https://www.semanticscholar.org/paper/fb20838a16fb552c80d0133f0a5f04dbb7f5922c) said:

> 지금까지 일부 연구자들에 의해 사질토 지반에서 수평반복하중을 받는 버켓기초의 거동에 대하여 연구 된 바 있다(e.g. Byrne, 2000; Villalobos, 2006; LeBlanc et al., 2010; Zhu et al., 2013).

[Bisoi et al.](https://www.semanticscholar.org/paper/289c4d2d0d489553c5fc0096e4d901c961071323) said:

> The load acting on the turbine blades (Fb) is estimated as (Jara 2006), sThubTab CVRF 225.0 (1) where is the wind load acting on the hub in N, Vhub is the wind speed at the hub height in m/s, RT is the rotor radius in m, ρa is the air density which equals to 1.23 km/m3 at 15C at 1 atm, CT(λs) is…

[Liu et al.](https://www.semanticscholar.org/paper/987dca007bdd98ab9625a377a47eefcfb78ff06f) said:

> Offshore Standard DNV-OS-J101, 213p. Villalobos Jara, F.A., 2006.


## Byrne, Houlsby(2003)

This paper explores the **civil engineering problems encountered for offshore wind turbines**. It reviews previous work on the design of offshore foundations and presents some simple design calculations for sizing foundations and structures appropriate to the wind-turbine problem.

• Offshore wind turbines are a viable alternative to onshore wind farms, as they can provide more energy and are less likely to be objected to on aesthetic grounds.

• The design of offshore foundations is a critical component of the engineering challenge, and current designs have deficiencies that need to be addressed.

• Research is currently underway to improve designs so that offshore wind turbines can compete economically with traditional energy suppliers.

[Whitehouse et al.](https://www.semanticscholar.org/paper/6a772e0aa5b88995d54109ae7e3017dbace16c43) said:

> For a review of the different foundation solutions see Byrne and Houlsby (2003). Gravity base foundations generally require substantial seabed preparations and where scour protection is installed below the level of the surrounding seabed there is the potential for sediment accretion changing what are potential hard substrates to silty/sandy seabeds and the possible accumulation of decaying macro-algae and the development of elevated nutrient levels. Therefore, the effects of sediment smothering, sediment accretion and scouring may lead to a corresponding reduction in benthic recruitment success, etc. The aim of the current paper is to evaluate the development of scour on the seabed from an analysis of monitoring results of data from built offshore windfarms, supplemented with reference to other published datasets. The sensitivity of a range of different seabed sediment environments to the physical process of scour is assessed. Knowledge of the scour that has developed to date around offshore windfarm foundations supplements the existing guidance available from Det Norske Veritas (DNV) (2007) and is also informative for other offshore renewable technologies.

[Westgate et al.](https://www.semanticscholar.org/paper/25e8f7178ed1ccd039818ca1a15406458cab12f1) said:

> A simplified design analysis for a single suction caisson foundation was also conducted by Byrne and Houlsby (2003).

[Arnoudt](https://www.semanticscholar.org/paper/627d4858cbe1e72b6f0ddcfaefe7f50539864121) said:

> Therefore, the foundation type is not used very often, especially not in Europe because of the unsuitable soil (Byrne and Houlsby, 2006) (EWEA, 2011).

[Nguyen et al.](https://www.semanticscholar.org/paper/a65e2c3dacc70969f8b5cb9f34246b39bf1a29b7) said:

> The results in Figure 5 show that the data points from this study were bounded by the ones from the two other studies, Byrne and Houlsby [6] and Wang, Zeng and Li [7].

[Jara et al.](https://www.semanticscholar.org/paper/e8ad0a606b52a4f8494a308fe51a435f53ddae24) said:

> Information about the project at Oxford can be found in Houlsby and Byrne (2000), Byrne et al. (2002), Byrne and Houlsby (2003, 2006) and Villalobos et al. (2004).

[Kelly et al.](https://www.semanticscholar.org/paper/eba8a9a0a37251eb5e8e0198bc0bccf42fbaa30d) said:

> Previous research on the transient tensile capacity of skirted foundations in saturated sand has been conducted by Bye et al (1995), Johnson (1999), Byrne (2000), Byrne and Houlsby (2002a) and Kelly et al (2003).

[Harte et al.](https://www.semanticscholar.org/paper/1ae22d3ccac144caf95f1063e2ef957e583e669e) said:

> Their application to offshore wind turbines is discussed by Byrne and Houlsby.(21,22) A fully operational 3.

[Cerfontaine et al.](https://www.semanticscholar.org/paper/d330f842a4436325372999fecbcf206cd8e6d297) said:

> Indeed their costs may represent up to a third of the total cost (Byrne & Houlsby, 2003; Senders, 2008).

## Qingpeng Li(2018)

This paper investigates the **effect of local scour on the behavior of mono-piles installed in sand under combined lateral and vertical loading**. It uses the Finite Element Method (FEM) and finds that **vertical loading can decrease pile lateral displacement and improve the lateral capacity of piles in the absence of scour and under scour**.

• Vertical loading can decrease pile lateral displacement and improve the lateral capacity of piles in the absence of scour and under scour. 

• The increase of scour depth will largely reduce lateral capacity of piles.

• The Finite Element Method (FEM) using PLAXIS can be used to simulate the behavior of mono-piles installed in sand under combined lateral and vertical loading.

[Liu et al.](https://www.semanticscholar.org/paper/0f8ccfdc629c0703671a5566c04251be6d6d64f4) said:

> The effects of scour hole geometry (Li, Han, and Lin 2013) are ignored under the assumptions of overall loss of the surface soil and a constant horizontal load of the suction caisson after scour (Lin et al. 2014a, 2016).

[Jia et al.](https://www.semanticscholar.org/paper/007a267768093d8fc235e0ff92faafff5aecbdcc) said:

> 5 D (9 m) for the case considered in this paper in which the slope angle is 30◦ based on Li and Qi’s test [9] and detailed procedures are as follows:

[Li et al.](https://www.semanticscholar.org/paper/6f0507659e38a6b79b437a3a1de5a471c979fc89) said:

> Marine Georesources & Geotechnology, 34: 747–758 Copyright # 2016 Taylor & Francis Group, LLC ISSN: 1064-119X print/1521-0618 online DOI: 10.1080/1064119X.2015.1087438 impact, and weather (Veeresh and Rao 1996; Byrne and Houlsby 2004; Li, Han, and Lin 2013).

[Rahimi et al.](https://www.semanticscholar.org/paper/363ef7ad2d9974f765852829c06dbf9a3cd02d54) said:

> Piers and abutments have also significant applications in marine environment (Li, Han, and Lin 2013).

## Cheng Lin(2014)

This paper discusses a **simplified method for the analysis of laterally loaded piles in sand under a scour condition**. The p-y curves in this method were based on a wedge type of failure. The effects of the scour hole dimensions on the response of laterally loaded piles in sand were evaluated using this simplified method.

• A simplified method was developed for the analysis of laterally loaded piles in sand under a scour condition. 

• The effects of the scour hole dimensions on the response of laterally loaded piles in sand were evaluated using this simplified method. 

• The computed results showed that the scour hole dimensions had a significant effect on the response of laterally loaded piles in sand.

[Wang et al.](https://www.semanticscholar.org/paper/41201a4a5feae9f7a3f55f354255e742372ba98f) said:

> This approach, however, may not reflect the real situations of bridges under scour conditions (Lin et al. 2014; Qi et al. 2016) because the scour effect is not well reflected in frequently used p-y 1Postdoctoral Research Associate, College of Civil and Transportation Engineering, Hohai Univ., 1…

[Qi et al.](https://www.semanticscholar.org/paper/7b62cf7ec2a9e42dbba888d28dc86dbade6068c1) said:

> It is noted that scour effects have not been well reflected in existing p–y curve methods, although the problem has been studied using numerical analysis (Lin et al., 2010, 2014).

[Liu et al.](https://www.semanticscholar.org/paper/0f8ccfdc629c0703671a5566c04251be6d6d64f4) said:

> The effects of scour hole geometry (Li, Han, and Lin 2013) are ignored under the assumptions of overall loss of the surface soil and a constant horizontal load of the suction caisson after scour (Lin et al. 2014a, 2016).

[Lin et al.](https://www.semanticscholar.org/paper/8fef156a339720eb291fb4880017477a1c760522) said:

> A case used by Lin et al. (2014) was used here.

[Another paper](https://www.semanticscholar.org/paper/7d2cc65781391ff25df57e2bfed53bfa90f219b9) said:

> Analyical and empirical models, which provide simple modifications to the original Reese et al. (1974) wedge p – y method, have since proven the conservatisms associated with this (Lin et al., 2014; Qi et al., 2016).

[Lin](https://www.semanticscholar.org/paper/2382011751d388c416e71502e10f60306ecdf9df) said:

> A handful of studies have been focused on the scour effects on lateral responses of bridge pile foundations (Lin et al, 2010, Lin et al., 2014, Lin et al., 2016, Zhang et al., 2017).

[Yang et al.](https://www.semanticscholar.org/paper/9d78f7f985df86f88b8be6de48b0a1e0b045d5c7) said:

> Consider the three-dimensional scour hole dimensions, Lin et al. (2014) modified the limiting soil resistance of the p–y curves in Reese et al. (1974) based on the wedge type of failure.

[Liu et al.](https://www.semanticscholar.org/paper/acb9766de5dd243db6c2050b4ea9d14c40472f5d) said:

> This change has been investigated and detailed in Lin et al. (2010, 2014b); in addition, a detailed procedure of iterative computation is presented in Liu et al. (2018).

## W Qi(2016)

Soil scour around a shallowly embedded pile can significantly reduce its **stiffness and capacity**.

• Soil scour around a shallowly embedded pile can significantly reduce its lateral stiffness and capacity. 

• Estimation of the lateral pile response must take into account the effects of scour.

• P-Y curves for shallowly embedded piles in sand are affected by scour.

[Wang et al.](https://www.semanticscholar.org/paper/41201a4a5feae9f7a3f55f354255e742372ba98f) said:

> This approach, however, may not reflect the real situations of bridges under scour conditions (Lin et al. 2014; Qi et al. 2016) because the scour effect is not well reflected in frequently used p-y 1Postdoctoral Research Associate, College of Civil and Transportation Engineering, Hohai Univ., 1…

[Boujia](https://www.semanticscholar.org/paper/f4f7fc16896b6af0234b45ffaa275f3016086ac7) said:

> On one hand, many empirical formulas are proposed in literature [4, 5, 6, 7].

[Jia et al.](https://www.semanticscholar.org/paper/007a267768093d8fc235e0ff92faafff5aecbdcc) said:

> To explore the lateral resistance of the remaining sand horizon under scouring, a centrifuge test is applied to make a comparison between the lateral soil resistance in the general scour and local scour [17], indicating that p-y curves for the local scour cases, sand horizon at a given depth below the scour pit base is much stiffer than that at the same depth below the original soil surface, while this characteristic is not founded in the general scour sand horizon.

[Zhu et al.](https://www.semanticscholar.org/paper/dbe6489e498d88ae3a05173868e02a8f1c6a29d5) said:

> All strain gauges were protected by epoxy resin (Qi et al. 2016; Zhu et al. 2019).

[Wu et al.](https://www.semanticscholar.org/paper/f4352d75bbf2b42d4c5ff1f8426fffa5ebcbc52a) said:

> Consequently, various methods, including but not limited to three-dimensional numerical simulations (Qi et al., 2016; Lin and Lin, 2019) and modified load transfer methods (Lin et al.

[Chortis](https://www.semanticscholar.org/paper/f8a2e5714c5ab72d6430cbf03ec7eba214592b01) said:

> …presented, that are the most common cases investigated in the literature (Hjorth, 1975; L. C. Reese et al., 1989; B. Mutlu Sumer et al., 1992; Whitehouse, 1997; Hoffmans & Verheij, 1997; Kishore et al., 2009; Whitehouse et al., 2011; Y. E. Mostafa, 2012; Petersen et al., 2015; Qi et al., 2016 ).

[Another paper](https://www.semanticscholar.org/paper/7d2cc65781391ff25df57e2bfed53bfa90f219b9) said:

> Analyical and empirical models, which provide simple modifications to the original Reese et al. (1974) wedge p – y method, have since proven the conservatisms associated with this (Lin et al., 2014; Qi et al., 2016).

[Qi et al.](https://www.semanticscholar.org/paper/8e584945711e1c2c2a68f41975ff7135932f180d) said:

> The p-y curves get progressively stiffer with ascending values of ze/D, confirming that the present numerical results are generally consistent with the centrifuge results from Qi et al. (2015).

## B Zhu(2014)


This paper investigates the **bearing capacity of suction caisson foundations of offshore wind turbines**. **Several series of model tests were carried out in sandy silt under 1g gravity on suction caissons with different sizes subjected to overturning loading**. A **new calculation approach of deflection-based bearing capacity was proposed based on the mechanics of the deformation process**.

• Model tests revealed the effect of the diameter, aspect ratio, and loading eccentricity on normalized moment capacity of caissons.

• The instantaneous rotation centers of model caissons were simplified to be at the depth of about four-fifths of the skirt length, almost directly below the lid center. 

• A new calculation approach of deflection-based bearing capacity was proposed based on the mechanical behavior of the caisson.

[Zhang et al.](https://www.semanticscholar.org/paper/3329b0a8a0be940fa88d4693673d73276eb391b7) said:

> Therefore, compared with the calculated MSC capacity by using methods proposed by Villalobos (2006) and Zhu et al. (2014) based on the rotation center position in the serviceability limit state, the calculated result based on the rotation center position in the ultimate limit state may be…

[Deb et al.](https://www.semanticscholar.org/paper/7cccc91b6defeaaa66e260b808b9c05f709340f3) said:

> limited by serviceability constraint of the wind tower [16].

[Wang et al.](https://www.semanticscholar.org/paper/aa8011ea2e4854712c2fd9671951d4f58586bdb0) said:

> The existing theoretical calculation methods and the checking methods in practical engineering for the ultimate bearing capacity of the bucket foundation usually need to determine the position of the foundation rotation centre firstly (Lian et al. 2011; Zhu et al. 2011, 2014).

[Liu et al.](https://www.semanticscholar.org/paper/0f8ccfdc629c0703671a5566c04251be6d6d64f4) said:

> The positions of the instantaneous rotation centers of the caissons can be simply considered to be at the depth of 0.8L, though the positions change with variation of the aspect ratio L/D (Zhu et al. 2014).

[He et al.](https://www.semanticscholar.org/paper/75eca236fbdc1fea7ba41c20a533ca401d72f4c3) said:

> CONATCT Shaoli Yang shaoli.yang@ngi.no Norwegian Geotechnical Institute (NGI), Oslo, Norway © 2020 Informa UK Limited, trading as Taylor & Francis Group China is developing continuously more and more offshore wind farm projects (Zhu et al. 2014).

[Faizi et al.](https://www.semanticscholar.org/paper/b7e64ebe6894260fbcc596028595d6e95f1dcc8c) said:

> 4 The bearing capacity of the single suction bucket foundations has been extensively 69 studied in different soil types [15, 18-20], whereas only a few studies have examined 70 the behaviour of tripod suction bucket foundations under lateral loading [21-23].

[Jiang et al.](https://www.semanticscholar.org/paper/8273da9a934334e5eedee3cc2502f9ce0bc377e1) said:

> Suction penetration of single-bucket foundations has been extensively studied by scale model tests [6,7], numerical simulations [8,9], and theoretical research [10,11].

[Deb et al.](https://www.semanticscholar.org/paper/5bfa67993ed801f5ae12ef898c7ef2d8e7ae4c76) said:

> Zhu et al. (2014) studied the overturning response of model caissons of different sizes and provided analytical formulation to estimate the deflection-based bearing capacity.

## Mayall(2018)

This paper describes a research project that develops a framework to assess the influence of scour and scour remediation systems on the dynamic characteristics of offshore wind turbine structures. The research project includes one-dimensional (1D) finite element modelling, calibrated using three-dimensional (3D) finite element analysis, experimental measurements, and monitored field data.

• A framework has been developed to assess the influence of scour and scour remediation systems on the dynamic characteristics of offshore wind turbine structures.

• The framework includes 1D and 3D finite element modelling, calibrated using experimental measurements and monitored field data. 

• A novel experimental programme was carried out on a 1:20 scale offshore wind structure in the Fast Flow Facility at HR Wallingford, UK.

[Couldrey et al.](https://www.semanticscholar.org/paper/814dadf90003cd29e8078848a5592c8effbc6da2) said:

> When designing a foundation its embedment depth is taken into consideration, since the overburden of the surrounding seabed material will affect the structure’s stiffness and, consequently, its dynamic response (Mayall et al., 2019).

## Xuefei Wang(2017)

This paper investigates the **lateral bearing behaviors of suction bucket foundations for offshore wind turbines** by **centrifuge modelling**. It tests three bucket foundation models with different aspect ratios in both lightly over-consolidated clay and heavily over-consolidated clay. The accumulated lateral displacements and secant stiffnesses are discussed, and their variations with cycle numbers are studied.

• Centrifuge tests were performed in lightly over-consolidated clay and heavily over-consolidated clay, and three bucket foundation models with aspect ratios of 0.38, 0.5, and 1.3 were tested.

• Ultimate bearing capacities of suction bucket foundations were extracted from load-displacement curves, and displacement rates were calculated to find critical bearing capacities and ultimate bearing capacities of the foundations.

• Cyclic tests included cyclic loads with uniform and increased amplitudes, and the accumulated lateral displacements and secant stiffnesses were discussed.

## Zhubin(2011)

This paper reports on **large-scale model tests** of suction installation and lateral loading of caisson foundations in saturated silt. It finds that the **seepage effect is limited in silt** and that the **deformation mechanism and soil-structure interaction of a caisson subjected to lateral loads** can be investigated.

• Seepage effect is limited in silt, and the suction required to penetrate the caisson can be predicted based on the sleeve friction and cone resistance of cone penetration tests. 

• The instantaneous rotation center of the model caisson at failure was at the depth of about four-fifths of the skirt length, almost directly below the lid center.

• The soil-structure interaction of a caisson subjected to lateral loads was investigated.

[Beemer](https://www.semanticscholar.org/paper/f1b02d65a13e4f992028d4d7cef90b36ead40c25) said:

> Additionally, Zhu et al. (2011) ran large scale laboratory tests on skirts with L/Ds of 0.5 in silt.

[Kim et al.](https://www.semanticscholar.org/paper/4ed3524ebdc496d2483ddceb0acb5192f8b33d02) said:

> 이를 감안하여 석션 버켓기초를 해상풍력타워에 적용하기 위한 연구가 전 세계적으로 활발하게 진행되 고 있으며(Houlsby and Byrne, 2000; Houlsby et al., 2005; Zhu et al., 2011), 기상탑에 대해서는 성공적으로 적용 된 사례가 보고되었다(LeBlanc et al., 2009; Recharge, 2012).

[Wang et al.](https://www.semanticscholar.org/paper/aa8011ea2e4854712c2fd9671951d4f58586bdb0) said:

> The existing theoretical calculation methods and the checking methods in practical engineering for the ultimate bearing capacity of the bucket foundation usually need to determine the position of the foundation rotation centre firstly (Lian et al. 2011; Zhu et al. 2011, 2014).

[Liu et al.](https://www.semanticscholar.org/paper/0f8ccfdc629c0703671a5566c04251be6d6d64f4) said:

> The calculation methods presented in Sections 2 and 3 are validated by comparison with test data obtained by large-scale model tests (Zhu et al. 2011).

[Choo et al.](https://www.semanticscholar.org/paper/f3c727430484a7b5a73624e8703ee6fbdb5a8578) said:

> 이중에서 석션기 초는 안정성과 효율성을 가진 경제적인 지지구조물로 주목받 아왔다(Houlsby et al., 2005; LeBlanc et al., 2010; Zhu et al., 2011; Hung and Kim, 2014; Kim et al., 2014a).

[Hein et al.](https://www.semanticscholar.org/paper/96b4e586cf2aa1522849932084f88bc0b93dc82d) said:

> Zhu, Kong, Chen, Kong, & Chen [9] tested skirts with aspect ratios of 0.

[Wang et al.](https://www.semanticscholar.org/paper/99e7edfc7d716b59d53efc7de4c8878b7f3fb25a) said:

> The foundation was carefully installed in the soil through a vacuum system (Erbrich and Tjelta 1999; Zhu et al. 2011) using the same installation process as Ding et al. (2015), and sufficient time was provided to ensure a steady state to be reached.

[Choo et al.](https://www.semanticscholar.org/paper/81c02262fccea2bfb66882161fd224fee0d7d9e6) said:

> et al., 2005; Gourvenec, 2007; LeBlanc et al., 2009; Zhu et al., 2011; Hung and Kim, 2012).

## Kelly,Houlsby(2006)

This paper compares **field and laboratory tests of caisson foundations in sand and clay**. It finds that the **laboratory data from moment loading tests were similar to the field data in most cases**, but the **laboratory and field data from vertically loaded caisson tests show more significant differences**.

• Laboratory tests applying vertical and moment loads to suction caissons founded in sand and clay were conducted to simulate an equivalent series of field tests.

• The non-dimensional laboratory data from moment loading tests were similar to the field data in most cases. 

• The non-dimensional data from vertically loaded caisson tests in the laboratory and in the field show more significant differences.

Suction caissons have been used to provide innovative solutions to deep-water foundation and anchoring problems during the last 15 to 20 years. For some of these projects, programmes of model testing designed to simulate prototype caisson behaviour have been conducted. Laboratory studies of small-scale model caissons at 1g include Larsen (1989), Steensen-Bach (1992) and El-Gharbawy & Olson (1998), whereas centrifuge studies were carried out by Watson et al. (2000), Bang et al. (2001), House & Randolph (2001) and Clukey et al. (2003). Published data from field trials using larger-scale caissons are less common, but include Hogervorst (1980), Tjelta (1986), Dyvik et al. (1993) and Cho et al. (2003). In most of these studies, the data are used to calibrate theoretical models, which are then used to predict prototype behaviour. No attempt has been made to compare directly the load-displacement response of caissons at different scales. Such comparisons are, however, vital if model testing is to be used to predict field behaviour.


[Nielsen](https://www.semanticscholar.org/paper/785096b22e824539a0f15af0316e59a8e8827c5e) said:

> Kelly et al. (2006) reported comparison of field and laboratory work. Comparisons are made both for vertically and moment loaded foundations. Here, only the comparison of the moment loaded foundation in sand will be summarised. The compared results are small-scale laboratory tests (diameter of 0.2 m and 0.3 m) and large-scale tests (diameter of 3.0 m) presented in Houlsby et al. (2006). The paper presents dimensionless equations to compare laboratory and field tests.

[Cox et al.](https://www.semanticscholar.org/paper/54468b2e980d6ea9d7f9c8cc9056d7b63f31a198) said:

> It was also necessary to scale the corresponding caisson response to extract the relevant data; this was achieved using the non-dimensional groupings suggested by Kelly et al. (2006) (and presented in Table 2), which permits comparisons between the results of this study with those conducted at different scales.

[Kelly et al.](https://www.semanticscholar.org/paper/d8653d02841fcad337cce6439864545e225574fb) said:

> Brief details of the tests presented in this paper are given in Table 2, and comprehensive descriptions of all 27 tests are given by Kelly et al. (2006b).

[Abadie et al.](https://www.semanticscholar.org/paper/60f4abe13081d18a81a5a69b350401bf0519181f) said:

> Large-scale field tests would enable the laboratory model scale pile behaviour to be related to that of real offshore wind monopiles in a similar manner to the work of Kelly et al. (2006) for suction caissons.

[Jara](https://www.semanticscholar.org/paper/863ec46b40f43350488ec7ce6d80073d40230625) said:

> Comparisons, in terms of a normalised Kmi (Kelly et al., 2006a), are shown in Figure 6.

[Villalobos et al.](https://www.semanticscholar.org/paper/df821a418105f197a9954368e58e1ec5857811ea) said:

> The value of shear modulus used in the calculation is based on the expression given by Kelly et al. (2006) and varied between 0.5 MPa and 2 MPa for the diŠerent tests.

[Abadie](https://www.semanticscholar.org/paper/ed4b7a2e143bab8557276a0622ab92ef39202645) said:

> 4: Moment loading caisson response from Kelly et al. (2006): (a) laboratory test data, 0.

[Zhu et al.](https://www.semanticscholar.org/paper/311c0015960e4e0960ea31f47b275b63718e0580) said:

> The use of the scaling relationships proposed by Kelly et al. (2006) requires that the values of h, ~e, and ~ V are the same in the laboratory and the field.


## BZhu(2013)

This paper presents the results of **cyclic loading tests** on a model shallow foundation (a caisson) in loose sand. It was found that the **accumulated settlement of the caisson increased with the number of cycles and cyclic amplitude**.

• The accumulated settlement of the caisson increased with the number of cycles and cyclic amplitude.

• A cyclic loading regime intermediate between one-way and full two-way cycling produced the largest rotation.

• The cyclic stiffness response of the caisson decreased with increasing cyclic amplitude.

[Foglia et al.](https://www.semanticscholar.org/paper/7387cfa75d2e663140ba5c33380554c5c71a3064) said:

> Series 2 Zhu et al. 2013 Figure 9: Tc parameter: Zhu et al., 2013 and experimental points of this work Figure 8: Tb parameter: Zhu et al., 2013, experimental points of this work and relative fit 11 By simply combining Equations 1 and 3 the accumulated rotation as a function of loading configuration…

[Lee et al.](https://www.semanticscholar.org/paper/fb20838a16fb552c80d0133f0a5f04dbb7f5922c) said:

> 또한 하중 재하방향이 양방향 재하일 경우, 일방향 하중 재하의 경우보다 누적 변위 발생량이 큰 것으로 나타났 다. Zhu et al.(2013)은 사질토 지반에 설치된 단일형 버 켓기초에 대하여 누적 변위량을 산정하기 위하여 다양 한 1-g 모형실험을 수행하였으며, 실험결과 반복횟수 및 수직하중의 크기가 증가함에 따라 누적 변위량이 증 가하는 것으로 나타났다.

[Chen et al.](https://www.semanticscholar.org/paper/0298d118799bf1b7dca4476569bcf6cdda467185) said:

> This is different from the 219 studies of Le Blanc et al. (2010) and Zhu et al. (2013) on the peak accumulated 220 rotation, and use of the ratio of 0( ) /Np s (θs is the rotation induced in a static 221 test at a load equivalent to the maximum cyclic load), for a monopile and a 222 mono-caisson,…

[Lin et al.](https://www.semanticscholar.org/paper/ba721072f9103297f5ce4253be116366511763d5) said:

> Small scale tests were conducted by Zhu et al. (2013) to investigate the performance of a suction pile in loose sand subjected to 10,000 cycles of loading.

[Cox et al.](https://www.semanticscholar.org/paper/f3f6a2cb2ad2f296317f0887427bdf7a2f45308b) said:

> In addition both Zhu et al. (2013) and Foglia et al. (2014) conducted cyclic load tests on caisson foundations, Zhu et al., (2013) reported a rotation coefficient of α = 0.39 for caissons in dry sand and Foglia et al., (2014) identified an exponent of α = 0.18 for caissons in saturated sand.

[Tu et al.](https://www.semanticscholar.org/paper/f025e2fb0af3c431e46cfeadf4b7c07b9d484744) said:

> To define the point of the ultimate lateral bearing capacity of the foundation, the method described by Zhu, Byrne, and Houlsby (2013) was used in this paper.

[Zhu](https://www.semanticscholar.org/paper/5b82b035453b742b631a5230ebdaebd3d69e0db5) said:

> Several recent studies (Zhu et al., 2013; Foglia et al., 2014; Cox et al., 2014; Nielsen et al., 2017a) utilised the framework of LeBlanc et al. (2010) for monopiles in sand and provided guidance for the prediction of caisson response in relation to relatively larger number of cycles.

[Zhu et al.](https://www.semanticscholar.org/paper/3e6829b6a90ff2a703efa988a9fefef76751efad) said:

> As in 127 Zhu et al. (2018), the caisson aspect ratio of skirt length over diameter in the centrifuge tests 128 was L/D = 0.5, which is realistic and has been adopted in other suction caisson research (e.g. 129 Zhu et al., 2013).

[Subbian](https://www.semanticscholar.org/paper/2f4a01cdb0b4f9374f13f06260fcdd97110ad8d1) said:

> Zhu et al (2013)[28] on an in-house experimental set-up that was capable of modelling under three degree-of-freedom loading device [25].

[Baek et al.](https://www.semanticscholar.org/paper/ec0886303d42a8c6a0aba70783fec9f88e2122ee) said:

> Also, Zhu, Byrne, and Houlsby (2013) conducted 10,000 cycles of cyclic lateral load tests on a model shallow foundation (a caisson) in dry loose sand, showing that the stiffness of a pile is almost constant with respect to the number of cycles.

[Shen et al.](https://www.semanticscholar.org/paper/2bea2b5c00dd1ee557d7d5d17305d3f1d0bc85d5) said:

> Senders (2009) and Zhu et al. (2013) conducted centrifuge tests and concluded that the maximum negative pressure is determined by the pullout rate, the soil permeability and the cavitation effect.

[Li et al.](https://www.semanticscholar.org/paper/2c63ac43d661ae41e726045312050a7806ae5cc5) said:

> …loading, the failure mechanism of the RSC and the deformation range of the soil around the RSC can be used to calculate bearing capacity of the RSC. Zhu et al. (2013) and Zhu (2011) conducted large-scale model tests on RSCs in saturated silt to investigate the interaction between soil and suction…

[Hirai](https://www.semanticscholar.org/paper/b0589402d0a02e4e5f265982cc77353d56490065) said:

> Zhu, Byrne, and Houlsby (2013) assessed experimentally cyclic response from suction caissons under long-term lateral cyclic loadings in sand.

## Doherty(2005)

This paper presents **solutions for stiffness coefficients to represent the elastic behavior of a caisson foundation embedded in soil**. It uses the **scaled boundary finite element method**, with **shell elements to represent the foundation**. The stiffness coefficients take into account **nonhomogeneity in the soil, the geometry of the foundation, and the contribution of the skirt of the caisson foundation**.

• A novel numerical technique, the scaled boundary finite element method, is used to calculate stiffness coefficients for caisson foundations embedded in nonhomogeneous elastic soil. 

• The stiffness coefficients take into account the possibility of nonhomogeneity in the soil, the geometry of the foundation, and the contribution to the stiffness of the skirt of the caisson foundation.

• Tabulated values allow a simple curve fit to the stiffness values to be employed for particular cases.

[Suryasentana et al.](https://www.semanticscholar.org/paper/bbef94c6bfc8389b121b36a858f4bd9c6f00ef07) critique this paper, **Doherty et al.**, by saying:

> Collectively, these 11 soil profiles are highly challenging for existing design methods (e.g. Doherty et al. 2005), as these design methods typically require an idealized shear modulus form and it is not straightforward to enforce a ‘best-fit’ of the idealized form (Eq.

[Mohammed](https://www.semanticscholar.org/paper/8256209a53df44b5141f339047c09a2cc51f94a9) critiques this paper, **Doherty et al.**, by saying:

> The comparison of the results obtained in the present study against those of Doherty et al. (2005) reflects that the Scaled Boundry Finite Element Method underestimates and for a high values of it means in the rigid domain, furthermore, this method underestimate for a small values of it mean in the…

[Cox et al.](https://www.semanticscholar.org/paper/54468b2e980d6ea9d7f9c8cc9056d7b63f31a198) said:

> Notation and load reference point utilised in the nondimensional groupings following the definitions of Doherty et al. (2005) Group No.

[Georgiou et al.](https://www.semanticscholar.org/paper/919e820c4b3b358178d2a7232d94ef39eb2eeee8) said:

> …element/finite element method, managed to provide tables with non-dimensional values of the static stiffnesses of a suction caisson, much like Doherty et al. (2005), but also took the problem a step further by investigating the impedance of suction caissons, in vertical and sliding-rocking…

[El-Marassi](https://www.semanticscholar.org/paper/4b3c8ac96b9d2da356d85f26f0ca68c0873b60f2) said:

> Subsequently, Doherty et al. (2005) extend the analysis to account for caissons fitted with flexible skirts.

[Bhattacharya et al.](https://www.semanticscholar.org/paper/0974e6fe6ab46044e857b553c6ea82277a219938) said:

> Based on the work of Doherty et al (2005) the non-dimensional flexibility of a suction caisson is given by: GD Et (4) where E = Elastic modulus of caisson skirt (GPa) t = Thickness of caisson skirt (mm) G = Shear modulus of surrounding soil (GPa) D = Diameter of the caisson (m) The above group can…

[Suryasentana et al.](https://www.semanticscholar.org/paper/5cc256ef0262f7d6177244c69c461bb38799e0c7) said:

> For the example case of 𝜈 = 0.2, 𝐿 𝐷⁄ = 1, 𝛼 = 0, 𝑑$%&'(/𝐷 =572 0.005, differences between the current work and the data in Doherty et al. (2005) for 𝐾N amount 573 to 4.8% and 7.4% for rigid and flexible caissons respectively.

[Nguyen-Sy](https://www.semanticscholar.org/paper/8189af022f2993df173613217b08bb01755f046a) said:

> 2 Elastic solution for caisson footing Based on a numerical study using the scaled boundary finite-element method, Doherty et al. (2004) have provided an accurate means of assessing the elastic behaviour of caisson footings (see Figure 2.

[Jara](https://www.semanticscholar.org/paper/863ec46b40f43350488ec7ce6d80073d40230625) said:

> 6 shows values of the caisson stiffness coefficients following the calculation procedure suggested by Doherty et al. (2005). The vertical, rotational, horizontal, and coupled stiffness coefficients KV , KM , KH , and KMH were calculated to assess the flexibility of the caissons compared with infinitely rigid caissons K∞ and caissons without skirt K0.

[Bo et al.](https://www.semanticscholar.org/paper/c1cbaa548219ff71c74645a9b60608751d3f1c3d) said:

> The results agree with the work by Doherty and Deeks (2003) and Doherty et al. (2005) who employed the scaled boundary finite element method to analyse the static stiffness of suction caissons embedded in non-homogeneous elastic soil.

## Y Choo(2021)

This paper investigates the **behavior of a monopod bucket foundation** in **silty sand**.

• Monopod bucket foundations subjected to combined moment and horizontal loads in silty sand exhibit a nonlinear behavior.

• The ultimate bearing capacity of the monopod bucket foundation increases with increasing horizontal load. 

• The ultimate bearing capacity of the monopod bucket foundation decreases with increasing moment load.


[Zhou et al.](https://www.semanticscholar.org/paper/5247f9ef56c72a575422521bebe5a7bb2422403e) said:

> A number of studies have been performed including centrifuge tests [2, 14, 25, 31, 33, 42], 1 g model tests [9, 16, 20, 34], numerical simulations [3, 18, 29, 30, 36, 38, 40] and analytical solutions [5, 32] to understand the behavior of caisson during penetration process, that covering the soil failure mechanism and the penetration resistance of caissons in soils.

## Dong-Joon Kim(2013)

This paper evaluates the **bearing capacity behaviour of a monopod suction bucket foundation for an offshore wind tower**. It uses a **centrifuge load test and numerical analyses**. The results show that the foundation has a good bearing capacity.

• A centrifuge load test and numerical analyses were performed to evaluate the bearing capacity behaviour of a monopod suction bucket foundation for an offshore wind tower. 

• The model soil was prepared to simulate a target site by using soil samples having similar properties and controlling relative density.

• A series of numerical analyses were performed to validate the experimental conditions and study the effects of self-weight, distance to the boundary and elastic modulus of the soil layer on the load - rotation curves.

[Choi](https://www.semanticscholar.org/paper/4c1b6bff4dadcb0bb271318c378b3c784fe23815) said:

> The numerical model was modified from a model used in Kim et al. (2013) and detailed descriptions are given for modeling and analysis procedures.

[Yoo et al.](https://www.semanticscholar.org/paper/41bdff2b423e8da9edebc6de28a7254cf16ca3c1) said:

> 한편, Kim et al.(2011)은 모형실 험을 통하여 모래지반에 근입된 석션파일의 인발 작용 점 및 인발각 변화에 따른 인발저항력과 변위거동에 대 해서 분석하였으며, Kim et al.(2012)은 수치해석을 이 용하여 점토지반에 설치된 Tripod 기초의 수직 및 수평 지지력 변화 특성 및 길이와 직경의 변화에 따른 수평지 지력 및 모멘트하중에 의한 영향에 대해서도 분석하였 다. 가장 최근 들어 Kim et al. (2013)은 해상풍력 기초로 사용되는 석션파일(버켓기초)을 대상으로 원심모형실 험 및 수치해석을 통하여…

## Youn-seok Kim(2017)

This paper presents experimental model results for tilting control of a suction bucket foundation consisting of three internal cells. Tilting control was performed by independently controlling the internal pressure of each cell. It was found that the tilting control was within 5° during the installation and operation stages.

• Tilting control of a single-basket suction bucket foundation was tested using a 1:100 scale model. 

• Tilting control was within 5° during the installation and operation stages. 

• Tilting control was achieved by combining positive and negative pressures of each cell.

[Robertson](https://www.semanticscholar.org/paper/a8a2434ab2cd285b185b0e9d50f3a25221a146be) critiques this paper, **Kim et al.**, by saying:

> Uncertainty quantification in the seakeeping field is also not well developed, and is only recently getting attention (see Kim and Hermansky, 2014, for a review).

[Park](https://www.semanticscholar.org/paper/5615f36f70ade8c97f43a218c279df8517db4aba) said:

> 또한, 해상에 설치되기 때문에 풍력, 파력, 조류력과 같은 반복하중과 및 세굴 등에 의해 기울어짐이 발생할 수 있다(Achmus et al., 2009; Kim et al., 2015; Kim et al., 2017).

[Robertson et al.](https://www.semanticscholar.org/paper/455a7e921b7f8b2ef87a328e9af4ab2b60589476) said:

> The International Towing Tank Conference (ITTC) has developed procedures and guidelines that provide more focused recommendations for assessing uncertainty in experimental hydrodynamics [5], seakeeping experiments [6], and offshore wind turbines [7].

## J Tempel(2004)

This paper discusses the **effects of scour on the design of offshore wind turbines**. It describes how scour can affect the **foundation length and stiffness, natural frequency, and fatigue variation** of a turbine. The paper concludes that scour can have a significant impact on the design of offshore wind turbines.

• Offshore structures on a sandy seabed are susceptible to scour, which affects the required foundation length and stiffness, has an effect on the structure’s natural frequency and may cause free-spanning of the J-tubes.

• Varying the scour depth from 0 to 13m does require more steel (longer pile) but does not seriously affect the dynamics and fatigue of the structure in this case.

• Care should be taken to avoid direct interference between natural and excitation frequencies, reducing the risk of large dynamic amplification and unwanted exponential increase of fatigue.

[Jamieson](https://www.semanticscholar.org/paper/2f83fb1b0234c82d7c7263db59eff0f9bf393d60) said:

> A literature survey was carried out in [63], which pointed to the conclusion that current design standards may over-estimate the scour depth, by recommending a depth of 1.

[Another paper](https://www.semanticscholar.org/paper/be5a40c0f1bbcc180af4fea99ac033bdc6c2fbca) said:

> from Measurement Data Since it is difficult to directly measure the impact of external loads on the dynamic system of the WTG, methods of Operational Modal Analysis (OMA) are used for the identification of the modal parameters.

[Haddorp](https://www.semanticscholar.org/paper/d0d9d4dbd4277dc1df028f372941b8dd350c327c) said:

> The installation of scour protection around the foundation pile of a wind turbine costs between € 150.000 and € 300.000 (Tempel et al., 2004; Van der Oord ACZ, 2003), so that about 3 billion euros need to be spent on scour protection for the planned projects in Europe.

[Tautz-Weinert et al.](https://www.semanticscholar.org/paper/477a4e3f5dc069649da59e2b6b2d284e8ad45f4f) said:

> Selected results of other natural frequency calculations for scour at monopiles from [8], [9] and [10] are added.

[Balluff et al.](https://www.semanticscholar.org/paper/54a73b7ae41cd3bbad8949c70a9f752fef1f5771) said:

> With regards to wave measurements there is a need in monitoring the wave states for load profiles, which may need to be adjusted during the turbine life cycle, turbine maintenance and cable repair or scour protection [28] (using numerical models trying to predict its extent).

[Yi et al.](https://www.semanticscholar.org/paper/52c6b6321cc35d032914968c3fb1e6c562a92a6d) said:

> 그리고 세굴에 의한 고유 주파수 분석을 수행한 기존 문헌에서는 말뚝 직경의 2.5배까 지 세굴깊이를 고려한 바 있다(Van Der Tempel et al., 2004).

[Jawalageri et al.](https://www.semanticscholar.org/paper/a4eabebe8e225f940ede7b874a38cb13a6edb742) said:

> However, presence of scour would reduce the embedment of piles in the soil which could cause changes on the global natural frequencies of the OWTs (Tempel et al. 2004).

[Tang et al.](https://www.semanticscholar.org/paper/d5519ac774f67a5d52bf2aa34e1de94cd0352190) said:

> Additionally, because the monopile foundation is mainly used to transmit lateral forces and most of the force is transmitted through the upper soil, the impact of scouring on the bearing capacity of a monopile foundation is greater than that for a multi-pile foundation [5].

[Abhinav et al.](https://www.semanticscholar.org/paper/b018088fb8feb7f6ca1909daa8272435b2c5de0f) said:

> The influence of scouring on the natural frequency of an OWT has been investigated by van der Tempel, Zaaijer, and Subroto (2004), Sørensen and Ibsen (2013), and Prendergast, Gavin, and Doherty (2015).

[Jiang et al.](https://www.semanticscholar.org/paper/76e5c78494a7a7231cb2f5abfcff96eed5026961) said:

> Tempel et al. (2004) found that the increase in scour depth from 0 to 2.5D could decrease the fundamental frequency of the integrated OWT system by 6% and decrease the fatigue life by a factor of 4.3 for a 2.75 MW OWT in sands at a site off the Dutch coast.

[Porter](https://www.semanticscholar.org/paper/85065826dc95137fc71457044cf1754e44deb08f) said:

> White (1940) described the balance of forces on a sediment particle, defining the conditions at which it will just start to move on a flat bed, known as initiation of motion. Shields (1936) conducted extensive laboratory testing of this, and adopted the non-dimensional critical Shields parameter to describe the conditions in which a given sediment would start to move.

## J Choi(2014)

This paper discusses a **centrifuge load test** for a **preliminary design of a monopod suction bucket foundation**. The **target site was the Yellow Sea of Korea** and the **prototype foundation was a steel monopod caisson with a diameter of 15.5m for a 3MW turbine**.

• A centrifuge load test was performed to evaluate the preliminary design of a monopod suction bucket foundation for a 3MW turbine in the Yellow Sea of Korea.

• Horizontal load and overturning moment were applied and monitored in the test, with vertical load being simulated by self-weight of the bucket model.

• Numerical analysis was performed to validate test conditions and compare the effects of soil parameters.

[Koh](https://www.semanticscholar.org/paper/1cc04034f0d67865bc68a3919fbaf50ce31550af) said:

> Investigations on the performance in layered soils are very limited e.g. in dense silty sand-sandy silt (Kim et al., 2013) and in sand-clay (Park and Park, 2017).
> 

## Sung-Ryul Kim(2019)

This paper evaluates the **moment bearing capacity of offshore bucket platforms in sand**. It uses **numerical modeling** to study the effects of **soil density, the diameter and embedment depth of the bucket** on the moment capacity. A **preliminary design equation** is suggested to estimate the moment bearing capacity.


• A three-dimensional finite element analysis was performed to evaluate the moment bearing capacity of the bucket platform.

• Moment capacity was influenced by the embedment depth and diameter of the bucket. 

• A preliminary design equation was suggested to estimate the moment bearing capacity.


## Plodpradit(2020)

This paper presents a **procedure for the coupled dynamic analysis of offshore wind turbine–jacket foundation-suction bucket piles**. It is found that the **system responses are significantly influenced by soil spring stiffness type**.

• A procedure for the coupled dynamic analysis of offshore wind turbine–jacket foundation-suction bucket piles was presented and compared the American Petroleum Institute (API) standard method and Jeanjean’s methods used to model the piles. 

Analyses of a laterally loaded single pile in a soft clay soil performed in both the X-SEA and Structural Analysis Computer System (SACS) programs showed good agreements.

• The behaviors of a five MW offshore wind turbine system in South Korea were examined by considering waves, current, wind effects, and marine growth. The natural frequencies resulting from Jeanjean’s method were higher than those from the API method. The system responses were significantly influenced by soil spring stiffness type.

[Zhou et al.](https://www.semanticscholar.org/paper/4a3b78a55386b092d144220de05c2ef05d932953) said:

> , offshore platforms [5], soft ground [6], artificial islands) faces great challenges when soft soil is encountered.

This paper presents a procedure for the coupled dynamic analysis of offshore wind turbine–jacket foundation-suction bucket piles and compares the American Petroleum Institute (API) standard method and Jeanjean’s methods used to model the piles. Nonlinear springs were used to represent soil lateral, axial, and tip resistances through the P–Y, T–Z, and Q–Z curves obtained by either API’s or Jeanjean’s methods. Rotational springs with a stiffness equated to the tangent or secant modulus characterized soil resistance to acentric loads. The procedure was implemented in X-SEA program. Analyses of a laterally loaded single pile in a soft clay soil performed in both the X-SEA and Structural Analysis Computer System (SACS) programs showed good agreements. The behaviors of a five MW offshore wind turbine system in South Korea were examined by considering waves, current, wind effects, and marine growth. In a free vibration analysis done with soil stiffness through the API method, the piles were found to bend in their first mode and to twist in the second and third modes, whereas the first three modes using Jeanjean’s method were all found to twist. The natural frequencies resulting from Jeanjean’s method were higher than those from the API method. In a forced vibration analysis, the system responses were significantly influenced by soil spring stiffness type. The procedure was found to be computationally expensive due to spring nonlinearities introduced.

## Klinkovort(2013)

This paper deals with **three different and important issues for centrifuge testing on monopiles for offshore wind turbines**.

• Centrifuge model tests on cylindrical stiff monopiles have been conducted to investigate the scaling issues.

• The results show that the centrifuge model tests can accurately predict the behavior of the full-scale monopiles. 

• The tests also revealed that the scaling factor of the centrifuge model tests should be adjusted to account for the differences in the soil properties.

[Klinkvort](https://www.semanticscholar.org/paper/9b21a96ea903b4dcf66d668c2588959b23abedc2) critiques this paper, **Klinkvort et al.**, by saying:

> cycles. This is still below the number of cycles for the fatigue limit state (N = 10(7)), but it is an improvement compared to the original design method which is based on tests with fewer than 50 cycles. In general, the model framework is similar to the one proposed by LeBlanc et al. (2010a), but differences between the models are seen.

[Alamouti et al.](https://www.semanticscholar.org/paper/15e49f340ba89301e88e0f53a6240dd0abcc81aa) said:

> On the subject of the present study, a dimensional analysis has been performed by Klinkvort et al. (2013) [18].

[Al-Baghdadi](https://www.semanticscholar.org/paper/832d43c5fef0f52ab148138da08192cbcf752e55) said:

> Therefore, the nonlinear distribution of the stress with depth should be considered when the pile models are tested in the centrifuge in order to avoid any scale effects (Klinkvort et al., 2013).

[Another paper](https://www.semanticscholar.org/paper/7d2cc65781391ff25df57e2bfed53bfa90f219b9) said:

> The ratio of model pile diameter (D = 50 mm) to sand d50 (= 0.17 mm) value was equal to 290, well above the limit of 88 for stiff piles outlined in Klinkvort et al. (2013), illustrating no expected grain size effects on pile response.

[Cerfontaine et al.](https://www.semanticscholar.org/paper/c022c07ec60184495d2df9f03490c7e1dae673fa) said:

> Previous work has shown that 1g installed and in-flight installed piles do not behave in the same manner when tested laterally (Klinkvort et al., 2013) and axially.

[Sharif et al.](https://www.semanticscholar.org/paper/334841d06a4b82d9baf043b7a1f7ca7385e8ed45) said:

> …field applied to the soil bed was set at 48g to 236 match the dry sand centrifuge tests of Davidson et al. (2019) which actually represented the 237 effective stress within a saturated prototype scale of 80 after the method developed by Li et al. 238 (2010) and validated by Klinkvort et al. (2013).

[Qi et al.](https://www.semanticscholar.org/paper/7b62cf7ec2a9e42dbba888d28dc86dbade6068c1) said:

> Centrifuge data presented by Klinkvort et al. (2013) indicate that the pile installation at 1g and the smooth epoxy finish on the piles would have contributed to the measured pile response being less stiff than that calculated by the S&L method.

[Truong et al.](https://www.semanticscholar.org/paper/769219b9449202ef1c1adde4dc88e2164ad47a8c) said:

> The trends found in centrifuge tests of Klinkvort et al. (2013) and Dyson & Randolph (2001) suggest that the softer variation of H/(σʹvL DL) with y/D seen in test UWA-M is, at least in part, due to its 1-g installation.

[Cerfontaine et al.](https://www.semanticscholar.org/paper/cbf385cb7530d00e897b86b6d5bee199f122f3aa) said:

> This approach has previously been validated for lateral pile loading by Klinkvort et al. (2013).

[Kunasegaram et al.](https://www.semanticscholar.org/paper/3c6a6601ee9fd65c9f63e34c1e24bd276a01b5e4) said:

> The lateral response of mono-pile foundations in sand was quite deeply investigated through 1 g laboratory tests and more sophisticated centrifuge models (LeBlanc et al. 2010; Abadie et al. 2019; Georgiadis et al. 1992; Verdure et al. 2003; Rosquoet et al. 2007; Klinkvort et al. 2013; Klinkvort and Hededal 2014).

[Yue et al.](https://www.semanticscholar.org/paper/2fbdd2e081eae1d0221970584187874b65e87749) said:

> Introduction Geomechanical model test is one of the most widely used approaches in field of geotechnical and geology research [1, 2].

[Davidson et al.](https://www.semanticscholar.org/paper/68a0600abe473d0c69f5fa54197727a83635524a) said:

> 3.1 Installation and loading system Previous investigations of the effects of installing model piles at 1g before subsequent testing at high-g levels observed significant differences in the response of the model pile compared to in-flight installation and testing (Klinkvort et al. 2013).

[Gupta et al.](https://www.semanticscholar.org/paper/7cc80957a2b57bafdfc834d0fc0adc3a59333233) said:

> Several researchers have performed FE analyses and centrifuge tests onmonopiles in sandy and clayey soils to investigate their load–displacement behaviour (Klinkvort et al. 2013; Haiderali et al. 2013) and found that the monopiles undergo deformations typically by rigid-body rotation about a pivot point.


## Qingpeng Li(2020)

This paper investigates the **impact of local and global scour erosion on the monotonic lateral response of a monopile in sand**. It uses centrifuge tests to assess the effect of scour on the performance of piles with low L/D. Results suggest that **scour has a significant impact on the lateral load-bearing capacity and stiffness of the pile**.

• Scour has a significant impact on the lateral load-bearing capacity and stiffness of the pile, leading to increases in bending moment magnitude along the pile shaft and lowering the location of peak pile bending moment. 

• The response varies with scour type, with global scour resulting in larger moments than local scour.

• The size of the local scour hole is found to have a significant impact on the pile response, suggesting that scour hole width should be explicitly considered in design.

[Li et al.](https://www.semanticscholar.org/paper/682a795f5cfcfe5991bb3b98e8e5125555b39be6) said:

> In terms of the boundary conditions, this is an issue for centrifuge modeling in general as the actuators used to apply loads may also inflict certain fixity to the test piles [4].

[Khan et al.](https://www.semanticscholar.org/paper/46b0fe2ec17d9a87ecaceb63fa972dc393dc7938) said:

> studied frequency-based scour detection from the perspective of identifying the physical meaning of predominant natural frequency, optimal location of sensors and the effect of scour hole shape.(25) They conclude that natural frequency reduces with scour progression, but the frequency values differ depending on whether the scour hole is symmetrical or unsymmetrical, due to differences in the soil constraints.

[Wang et al.](https://www.semanticscholar.org/paper/90a0cd8885b76dc976b10d9cd88f86196772ec7c) said:

> Given that erosion can lead to a shift in soil texture, soil organic matter, and soil nutrients, resulting from loss of fines and organic matter which is detrimental to the soil structure, the soil water holding capacity, and crop productivity, considerable effort is being made to predict sediment detachment and transport rates [1,6].

The majority of offshore wind turbines (OWTs) constructed to date are founded on monopile foundations. Developments in construction methods and improved design procedures (Byrne et al. 2015a(Byrne et al. , 2018 have resulted in a gain in market share for monopiles from approximately 75 % of OWT foundations in 2012 (Doherty and Gavin 2012) to more than 87 % in 2017 (Wind Europe 2017) .

