---
title: "Reading Note"
jupyter: python3
---
11111
## **Centrifuge Test**

### Comparison of the dynamic responses of monopiles and gravity base foundations for offshore wind turbines in sand using centrifuge modelling

Monopiles and gravity base foundations (GBF) are two of the most commonly used foundations for offshore wind turbines. As resonance can cause damage and even failure of wind turbines, understanding the difference between the dynamic responses of monopiles and GBFs under free vibration is important. However there is little experimental data regarding their natural frequency, especially from model tests carried out at correct stress levels. This paper presents the results of novel monopile and GBF tests using a centrifuge to directly determine the natural frequency (fn) of the foundation-soil system. The natural frequencies of wind turbine monopiles and GBFs in centrifuge models were measured during harmonic loading using a piezo-actuator, with the results confirming that soil-structure interaction must be considered to obtain the system’s natural frequency as this frequency reduces substantially from fixed-base values. These results will contribute in preventing resonance induced damage in wind-turbines

#### 3 bullet points summary

-   Monopiles and GBFs are commonly used foundations for offshore wind turbines.
-   Understanding the dynamic responses of these foundations under free vibration is important to prevent damage and failure due to resonance.
-   This paper presents novel tests to determine the natural frequency of the foundation-soil system, conducted using a centrifuge with harmonic loading and a piezo-actuator. The results confirm that soil-structure interaction must be considered to obtain the system’s accurate natural frequency, which reduces from fixed-base values and will contribute to preventing resonance-induced damage in wind turbines.

### Assessment of bridge natural frequency as an indicator of scour using centrifuge modelling

One of the most prevalent causes of bridge failure around the world is “scour”—the gradual erosion of soil around a bridge foundation due to fast-flowing water. A reliable technique for monitoring scour would help bridge engineers take timely countermeasures to safeguard against failure. Although vibration-based techniques for monitoring structural damage have had limited success, primarily due to insufficient sensitivity, these have tended to focus on the detection of local damage. High natural frequency sensitivity has recently been reported for scour damage. Previous experiments to investigate this have been limited as a result of the cost of full-scale testing and the fact that scaled-down soil-structure models tested outside a centrifuge do not adequately simulate full-scale behaviour. This paper describes the development of what is believed to be the first-ever centrifuge-testing programme to establish the sensitivity of bridge natural frequency to scour. A 1/60 scale model of a two-span integral bridge with 15 m spans was tested at varying levels of scour. For the fundamental mode of vibration, these tests found up to a 40% variation in natural frequency for 30% loss of embedment. Models of three other types of foundation, which represent a shallow pad foundation, a deep pile bent and a deep monopile, were also tested in the centrifuge at different scour levels. The shallow foundation model showed lower frequency sensitivity to scour than the deep foundation models. Another important finding is that the frequency sensitivity to “global scour” is slightly higher than the sensitivity to “local scour”, for all foundation types. The level of frequency sensitivity (3.1–44% per scour depth equivalent to 30% of embedment of scour) detected in this experiment demonstrates the potential for using natural frequency as an indicator of both local and global scour of bridges, particularly those with deep foundations.

#### 3 bullet points summary

-   Scour, or soil erosion around bridge foundations due to fast-flowing water, is a common cause of bridge failure worldwide.
-   A reliable technique for monitoring scour would help bridge engineers take timely countermeasures to prevent failure.
-   This paper describes the first-ever centrifuge-testing program to establish the sensitivity of bridge natural frequency to scour. The tests found significant variation in natural frequency for different foundation types and levels of scour, demonstrating the potential for using natural frequency as an indicator of both local and global scour, particularly for bridges with deep foundations.

### Dynamic response of monopiles in sand using centrifuge modelling

Monopiles are one of the most commonly used offshore foundation for wind turbines. Their static capacity, p-y curve and cyclic loading behaviour have been studied using 1 g tests and centrifuge tests, but there is little experimental data regarding their natural frequency, especially using centrifuge testing. The design of offshore wind turbine foundations is largely governed by natural frequency as resonance due to cyclic loading can cause damage and even failure. Understanding the dynamic response of the monopile under free vibration is thus critical to design. This paper presents the results of novel monopile (large diameter) and single pile (small diameter) tests in a centrifuge to for the first time directly determine the natural frequency (fn) of the pile-soil system. An experimental methodology was used to define the natural frequency via measured acceleration and force time histories and their fast Fourier transforms (FFT) under a force applied at a controlled frequency. The effects of pile diameter, embedded length, free length of the tower and soil density on fn were investigated in the centrifuge tests. The same models used in the centrifuge test at 50 g were also tested at 1 g in order to assess the relevance of earlier 1 g investigations into system behaviour. The measured natural frequency of wind turbine monopiles in centrifuge models during harmonic loading from a piezo-actuator, confirmed that soil structure interaction at an appropriate stress level must be taken into account to obtain the correct natural frequency. The experimental data was compared to theoretical solutions, giving important insights into the behaviour of these systems.

#### 3 bullet points summary

-   Monopiles are commonly used offshore foundations for wind turbines.
-   There is limited experimental data on their natural frequency, especially using centrifuge testing.
-   The paper presents the results of novel tests in a centrifuge to directly determine the natural frequency of the pile-soil system. The effects of factors such as pile diameter, embedded length, free length of the tower, and soil density on natural frequency were investigated. The results showed that soil-structure interaction at an appropriate stress level must be considered to obtain the correct natural frequency and were compared to theoretical solutions.

### 정영훈 2021 Centrifuge modeling for the evaluation of the cyclic behavior of offshore wind turbine with tripod foundations

In this study, the cyclic responses of an offshore wind turbine with a tripod foundation installed on an actual site were evaluated in a centrifuge. To understand the behavior of the turbine at the site, the site soil conditions, environmental loads, and real offshore wind turbine structure installed at the actual site were modeled by considering the centrifuge scaling law. From a series of cyclic loading tests, the cyclic responses of the tripod foundation were evaluated in terms of temporary/permanent displacements and cyclic stiffness. Moreover, the long-term behavior of the tripod foundation was predicted from the experimental results. The test results showed that the initial stiffness of the soil–foundation system decreased as the loading amplitude increased and that the stiffness increased with the number of cycles due to soil densification. The findings revealed that the cyclic behaviors of the tripod were more affected by the load amplitude than the number of cycles. In addition, the permanent rotation increased logarithmically with the number of cycles. A simple method to predict the displacement and change in the foundation stiffness of the actual wind turbine is proposed based on the results of the model tests. The results of this study also provide key insights into the long-term cyclic behavior of tripod foundations for offshore wind turbines.

#### 3 bullet points summary

1.  Low cycle fatigue is a critical design factor for steel structures and machine components.
2.  The use of finite element analysis software is becoming popular for predicting fatigue endurance.
3.  This paper shows successful coupling of Abaqus/FEA and fe-safe software for uni-axial fatigue behavior prediction of a stainless steel specimen and verifies the results against experimental literature. Sensitivity to surface roughness and material model was also analyzed.

## **Finite Element**

### Simulation of Low Cycle Fatigue with Abaqus/FEA

Low cycle fatigue is an important design consideration for large steel structures and metallic machine components. Accurate prediction of fatigue endurance is essential to design the elements subjected to fatigue. The design guidelines given in codes of practices are applicable only to simple shapes and laboratory experimental verification is costly. Therefore simulation using finite element software is becoming popular. This paper demonstrate successful coupling of Abaqus/FEA and fe-safe software in predicting the uni-axial fatigue behaviour of a stainless steel specimen. The simulated results are verified against experimental results available in literature. Sensitivity to surface roughness and material model were examined.

#### 3 bullet points summary

-   The paper demonstrates the successful coupling of Abaqus/FEA and fe-safe software in predicting the uni-axial fatigue behavior of a stainless steel specimen.
-   The simulated results are verified against experimental results from literature.
-   The sensitivity of the results to surface roughness and material model are also examined.

### Effect of scour on the structural response of an offshore wind turbine supported on tripod foundation

A simplified scour model for tripod foundation taking into account both local scour and global scour is proposed in this paper. The model is incorporated into a three-dimensional (3D) finite element model for analysis of a full-scale offshore wind turbine founded on a tripod structure using realistic structural properties. Applicability of the 3D finite element model is validated using full-scale load test data. Four different scour conditions under two wave situations are examined for the ultimate limit state (ULS), serviceability limit state (SLS) and fatigue limit state (FLS). The results show that scour has a minor effect on the natural frequency of the tripod-supported wind turbine but can significantly increase the maximum cross-sectional von Mises stress of piles under the ULS and increase the deflection of piles within nearly 20 m below the original seabed under the SLS. As for the fatigue life of the tripod structure, it can also be reduced by the effect of scour. These findings provide insights which are useful for development of safe and economic design of offshore wind turbines supported by tripod foundations.

#### 3 bullet points summary

-   A simplified scour model for tripod foundation is proposed in the paper to take into account both local and global scour.
-   The model is incorporated into a 3D finite element model and validated using full-scale load test data.
-   The results show that scour has a minor effect on the natural frequency of the tripod-supported wind turbine but significant effects on the maximum stress of piles and the fatigue life of the structure under various limit states.

### Numerical modelling of the effects of foundation scour on the response of a bridge pier

Foundation scour can have a detrimental effect on the performance of bridge piers, inducing a signiﬁcant reduction of the lateral capacity of the footing and accumulation of permanent settlement and rotation. Although the hydraulic processes responsible for foundation scour are nowadays well known, predicting their mechanical consequences is still challenging. Indeed, its impact on the failure mechanisms developing around the foundation has not been fully investigated. In this paper, numerical simulations are performed to study the vertical and lateral response of a scoured bridge pier founded on a cylindrical caisson foundation embedded in a layer of dense sand. The sand stress–strain behaviour is reproduced by employing the Severn-Trent model. The constitutive model is ﬁrstly calibrated on a set of soil element tests, including drained and undrained monotonic triaxial tests and resonant column tests. The calibration procedure is implemented considering the stress and strain nonuniformities within the samples, by simulating the laboratory tests as boundary value problems. The numerical model is then validated against the results of centrifuge tests. The results of the simulations are in good agreement with the experimental results in terms of foundation capacity and settlement accumulation. Moreover, the model can predict the effects of local and general scour. The numerical analyses also highlight the impact of scouring on the failure mechanisms, revealing that the soil resistance depends on the hydraulic scenario.

#### 3 bullet points summary

-   Foundation scour can negatively impact the performance of bridge piers by reducing lateral capacity and causing permanent settlement and rotation.
-   Predicting the mechanical consequences of foundation scour is challenging due to the lack of investigation on its impact on the failure mechanisms around the foundation.
-   In this paper, numerical simulations are performed to study the vertical and lateral response of a scoured bridge pier using a calibrated Severn-Trent model. The model is validated against experimental results and shows the ability to predict the effects of scour on the foundation capacity, settlement accumulation, and soil resistance depending on the hydraulic scenario.

### Simulation of low cycle fatigue with Abaqus/FEA

Low cycle fatigue is an important design consideration for large steel structures and metallic machine components. Accurate prediction of fatigue endurance is essential to design the elements subjected to fatigue. The design guidelines given in codes of practices are applicable only to simple shapes and laboratory experimental verification is costly. Therefore simulation using finite element software is becoming popular. This paper demonstrate successful coupling of Abaqus/FEA and fe-safe software in predicting the uni-axial fatigue behaviour of a stainless steel specimen. The simulated results are verified against experimental results available in literature. Sensitivity to surface roughness and material model were examined.

#### 3 bullet points summary

-   The study evaluates the cyclic responses of an offshore wind turbine with a tripod foundation installed on an actual site.
-   The results of the tests showed that the stiffness of the soil-foundation system decreases with increasing load amplitude, but increases with the number of cycles due to soil densification.
-   The study proposes a simple method to predict the displacement and change in foundation stiffness of the actual wind turbine based on the results of the model tests.

### Effect of scour on the structural response of an offshore wind turbine supported on tripod foundation

Abstract   A simplified scour model for tripod foundation taking into account both local scour and global scour is proposed in this paper. The model is incorporated into a three-dimensional (3D) finite element model for analysis of a full-scale offshore wind turbine founded on a tripod structure using realistic structural properties. Applicability of the 3D finite element model is validated using full-scale load test data. Four different scour conditions under two wave situations are examined for the ultimate limit state (ULS), serviceability limit state (SLS) and fatigue limit state (FLS). The results show that scour has a minor effect on the natural frequency of the tripod-supported wind turbine but can significantly increase the maximum cross-sectional von Mises stress of piles under the ULS and increase the deflection of piles within nearly 20m below the original seabed under the SLS. As for the fatigue life of the tripod structure, it can also be reduced by the effect of scour. These findings provide insights which are useful for development of safe and economic design of offshore wind turbines supported by tripod foundations.

#### 3 bullet points summary

-   Low cycle fatigue is a significant design consideration for steel structures and metallic machine components.
-   Design guidelines in codes of practices only apply to simple shapes, and laboratory verification is expensive, leading to an increasing use of finite element simulation.
-   The paper presents a successful coupling of Abaqus/FEA and fe-safe software to predict the uni-axial fatigue behavior of a stainless steel specimen, verified against experimental results and examined for sensitivity to surface roughness and material model.

## **Operational Modal**

### Artificial and Natural Excitation Testing of SWiFT Vestas V27 Wind Turbines

The Scaled Wind Farm Technology facility has been developed by Sandia National Laboratories to enable rapid, cost-efficient testing and development of transformative wind energy technology. As part of this effort, ATA Engineering was contracted by Sandia to perform modal testing on multiple fully assembled wind turbines to gain a better understanding of the structures.


### Ambient and forced-vibration tests of the Beauharnois suspension bridge

Ambient and forced vibration tests were carried out on the Beauharnois Bridge, a unique, 177-m combined suspension and cable-stayed structure near Montreal. A rehabilitation program was completed on the bridge during which the deck was completely rebuilt with an orthotropic slab on two steel trusses. The rehabilitation program also included the addition of two pairs of stay cables on both towers, creating a hybrid suspension system. The paper presents a series of dynamic tests performed to evaluate the dynamic properties and the dynamic ampliﬁcation factor (DAF) for the rehabilitated bridge. The experimental program involved the measurement of vertical, transverse, and longitudinal acceleration responses of the deck and tower under ambient and controlled trafﬁc loads. Displacement, strain, and integrated acceleration DAFs were computed under different loading conditions. Modal properties were evaluated and used to correlate a three-dimensional ﬁnite element model for the bridge, including nonlinear cable behaviour. The paper discusses the experimental setup and the techniques used to evaluate vibration frequencies, mode shapes, and the DAF. Correlation of numerical dynamic properties and experimental results is also presented. Key words: cable-stayed bridge, dynamic ampliﬁcation, dynamic testing, numerical correlation, modal analysis, suspension bridge.

#### 3 bullet points summary

1.  Dynamic tests were carried out on the Beauharnois Bridge, which underwent a rehabilitation program to rebuild its deck and add stay cables.
2.  The tests measured acceleration, displacement, strain, and dynamic amplification factors (DAF) under ambient and controlled traffic loads.
3.  The modal properties of the bridge were evaluated and compared with a three-dimensional finite element model, including nonlinear cable behavior. The results showed correlation between the numerical and experimental dynamic properties.

### 유무성 2021  Closed form solutions for predicting lateral response of tripod suction pile for offshore wind turbine foundation

This study presents a simplified analysis technique capable of predicting the dynamic behavior of a tripod suction pile subjected to a horizontal load. The first natural frequency of the system, horizontal displacement, and allowable rotation angle at the pile head were set as target physical quantities in accordance with substructure design requirements. In consideration of the physical characteristics of the tripod suction pile, the analysis was extended to the single pile-multi-pile-tripod-tower part to derive the influence factors. A possible displacement response function that could be applied to the intermediate pile range was also proposed. Thereafter, a detailed design was determined using an integrated load analysis, which included a turbine based on the basic design of simplified analysis method. Furthermore, the dynamic behavior of the offshore wind turbine at each installation stage was predicted using a numerical analysis and measured via field tests. The displacement at the pile head and the predicted value of the first natural frequency of the system were compared using the field-measured and numerical analysis values. The first natural frequency value produced by the simple analysis method showed an error range within 1%, and the displacement at the pile head also satisfied the structural design requirements. Therefore, this method provides a quick and accurate solution to the lateral response of tripod suction piles as foundations for offshore wind turbines

#### 3 bullet points summary

-   A simplified analysis technique was developed for predicting the dynamic behavior of a tripod suction pile subjected to a horizontal load.
-   The analysis was extended to consider the influence factors for the single pile-multi-pile-tripod-tower system.
-   The proposed method showed a small error range within 1% for the first natural frequency value and satisfied the structural design requirements for the displacement at the pile head, providing a quick and accurate solution for the lateral response of tripod suction piles as foundations for offshore wind turbines.

### 박광희 2022  Natural frequency degradation prediction for offshore wind turbine structures

The scale of offshore wind turbines (OWTs) has increased in order to enhance their energy generation. However, strong aero/hydrodynamic loads can degrade the dynamic characteristics of OWTs because they are installed on soft seabeds. This degradation can shorten the structural life of the system; repetitive loads lead to seabed softening, reducing the natural frequency of the structure close to the excitation frequency. Most of the previous studies on degradation trained prediction algorithms with actual sensor signals. However, there are no actual sensor data on the dynamic response of OWTs over their lifespan (approximately 20 years). In order to address this data issue, this study proposes a new prediction platform combining a dynamic OWT model and a neural network-based degradation prediction model. Specifically, a virtual dynamic response was generated using a three-dimensional OWT and a seabed finite element model. Then, the LSTM model was trained to predict the natural frequency degradation using the dynamic response as the model input. The results show that the developed model can accurately predict natural frequencies over the next several years using past and present accelerations and strains. In practice, this LSTM model could be used to predict future natural frequencies using the dynamic response of the structure, which can be measured using actual sensors (accelerometers and strain gauges).

#### 3 bullet points summary

1.  The increase in the scale of offshore wind turbines (OWTs) leads to strong aero/hydrodynamic loads and can result in the degradation of their dynamic characteristics.
2.  Previous studies on degradation used actual sensor signals for prediction algorithms but there are no actual sensor data on the dynamic response of OWTs over 20 years.
3.  A new prediction platform is proposed combining a dynamic OWT model and a neural network-based degradation prediction model, which can accurately predict natural frequencies over several years using accelerations and strains as inputs.

### SCALING FACTOR ESTIMATION BY THE MASS CHANGE METHOD

When natural input modal analysis is performed, the acting forces are unknown; by this reason only un-scaled mode shapes may be obtained so that the FRF matrix can not be constructed. If the structure is modified and a new modal testing is carried out, the scaling factors can be determined using the modal parameters (natural frequencies and mode shapes) from both the modified and the unmodified structure. Mass change is in many cases the simplest way to perform structural modification, which involves repeated testing implying mass change in different points of the structure where the mode shapes are known. In this paper, several methods to estimate the scaling factors, based on the mass change method, are presented. The accuracy obtained through the methods proposed depends on the type of normalization used in the mode shapes, the mass change magnitude and the number and the location of the masses attached to the structure, which effect is also analyzed. Finally, it is shown how the scaling factors can be used to improve the modal updating procedures.

#### 3 bullet points summary

1.  Natural input modal analysis yields only un-scaled mode shapes because the acting forces are unknown.
2.  Modal testing can be repeated after making a structural modification, such as mass change, to determine scaling factors.
3.  Several methods for estimating scaling factors based on mass change are presented, with accuracy dependent on mass change magnitude, normalization used, and number/location of attached masses.

### Load Estimation from Natural Input Modal Analysis

One application of Natural Input Modal Analysis consists in estimating the unknown load acting on structures such as wind loads, wave loads, traffic loads, etc. In this paper, a procedure to determine loading from a truncated modal model, as well as the results of an experimental testing programme, are presented. The method involves the inversion of the FRF matrix partly solving the numerical problems that appear because of the truncation of the modal space. However, the error in the load estimation depends on the degree of truncation of the modal space and on the accuracy of the modal parameter estimation. In the experimental program a small structure subjected to vibration was used to estimate the loading from the measurements and the experimental modal space. The modal parameters were estimated by Natural Input Modal Analysis and the scaling factors of the mode shapes obtained by the mass change method [ 2] [ 3] [ 4]. Finally, the calculated loading is compared with the actual loading in order to determine the magnitude of the errors.

#### 3 bullet points summary

1.  Ambient and forced vibration tests were conducted on the Beauharnois Bridge, a combined suspension and cable-stayed structure near Montreal, after a rehabilitation program.
2.  The rehabilitation program included the complete rebuilding of the deck with an orthotropic slab and the addition of two pairs of stay cables on both towers.
3.  The dynamic tests measured acceleration responses of the deck and tower under ambient and controlled traffic loads, evaluated modal properties and correlated a 3D finite element model with experimental results.


### Modal Estimation of Civil Structures Subject to Ambient and Harmonic Excitation

In this paper addresses the problems of separating structural modes and harmonics arising from sinusoidal excitation. Though the problem is mostly know in mechanical engineering applications such as rotating machinery, some civil engineering applications experiences the same challenges. A robust and fast harmonic detection procedure is presented and illustrated on a civil engineering case. In this paper, we have presented a fast algorithm for detection of harmonics from sinusoidal excitation. A statistical assessment algorithm of potential harmonics, based on evaluation of the Kurtosis of band pass filtered measurement, has been introduced. The speed of this algorithm has been optimized by applying a search algorithm that looks for abrupt changes in more than one singular value at a certain frequency, since this is a typical phenomenon in case of harmonics. This search algorithm typically increases the performance of the statistical assessment algorithm significantly. The harmonic detection approach has been demonstrated on measurements from a gravity dam

#### 3 bullet points summary

1.  The paper presents a fast algorithm for the detection of harmonics from sinusoidal excitation.
2.  The algorithm uses statistical assessment and optimization techniques for increased performance.
3.  The harmonic detection approach is demonstrated on measurements from a gravity dam in civil engineering.

### EXPERIMENTAL METHODS USED IN SYSTEM IDENTIFICATION OF CIVIL ENGINEERING STRUCTURES

To experimentally identify the dynamic characteristics of a structure, also referred to as system identification, two methods are available: Forced Vibration Testing (FVT) and Ambient Vibration Testing (AVT). The basic ideas of these methods are shortly presented. The main part of the paper deals with practical problems which are to be overcome when performing such a system identification test. To achieve reliable, good quality results, a number of parameters have to be optimized when planning an experimental system identification investigation. Among others, such parameters may be the means and location of excitation, the density of the measurement point grid, the sampling rate and the length of the time window. As an illustration, several examples of good and worse tests on bridges and other civil engineering structures are discussed.

#### 3 bullet points summary

-   Two methods of system identification (dynamic characterization of structures) are introduced: Forced Vibration Testing (FVT) and Ambient Vibration Testing (AVT)
-   A number of parameters must be optimized to achieve reliable results in system identification tests, including means and location of excitation, density of measurement points, sampling rate, and time window length.
-   Several examples of successful and unsuccessful system identification tests on bridges and civil engineering structures are discussed.

### Modal Based Fatigue Monitoring of Steel Structures

In this paper it is shown how the accumulated fatigue in steel structures can be estimated with high accuracy by continuously measuring the accelerations in a few points of the structure. First step is to obtain a good estimate of the mode shapes by performing a natural input modal analysis. The so obtained mode shapes are then used to calibrate a Finite Element model of the structure and to obtain the modal coordinates of the active modes by inverting the mode shape matrix. If the number of active modes is smaller than the number of measurement points, then the problem is solved by regression. If the number of active modes is larger then the number of measurement points, then the number of active modes is reduced by band pass filtering. Once the modal coordinates are identified and thus the complete response is established in the modal domain, then the information is mapped to the physical domain by applying the mode shapes of the calibrated Finite Element model and strains are obtained using the shape functions for the actual elements. The technique has been applied on a model frame structure in the laboratory and on a wind loaded lattice pylon structure. In both cases the estimated stresses has been compared with direct strain gauge measurements and it appears that the difference between the strains measured by strain gauges and the strains estimated by the presented technique is quite small. Looking at the fatigue of the lattice pylon it appears that the estimated damage is significantly smaller than the damage forecasted by commonly accepted design rules. This points to possibilities of significantly increasing the fatigue lives of structures by performing continuous monitoring

#### 3 bullet points summary

1.  The paper presents two methods for experimentally identifying the dynamic characteristics of a structure: Forced Vibration Testing (FVT) and Ambient Vibration Testing (AVT).
2.  Practical problems have to be overcome when performing system identification tests, including optimizing parameters such as the means and location of excitation, measurement point density, sampling rate, and time window length.
3.  The paper provides examples of good and bad tests on bridges and other civil engineering structures to illustrate the importance of these parameters in achieving reliable results.

### A GENERAL FRAMEWORK FOR DAMAGE DETECTION WITH STATISTICAL DISTANCE MEASURES: APPLICATION TO CIVIL ENGINEERING STRUCTURES

Detecting damage in structural systems is often achieved by a statistical comparison of damagesensitive characteristics of a structure evaluated on baseline data, against the corresponding characteristics obtained using data collected from a potentially defective structure. While several vibration-based methods have been proposed and successfully applied to detect damage in both mechanical and civil structures over the past years, the general framework describing their common properties and unifying the statistical decision about damage has mainly been elaborated in the control community. In this paper, we revise this framework in the context of detecting damage in structural systems. The statistical properties of three commonly used damage detection methods are recalled, and it is shown that their evaluation for damage boils down to a simple statistical distance. The framework is adopted to a commercial structural health monitoring software suite and its practical merit is illustrated on damage detection of two full-scale highway bridges.

#### 3 bullet points summary

1.  The paper discusses a method to accurately estimate the accumulated fatigue in steel structures.
2.  The method involves performing natural input modal analysis to obtain mode shapes, calibrating a Finite Element model, reducing the number of active modes by filtering if needed, and mapping the modal information to the physical domain.
3.  The technique has been applied on a laboratory model frame structure and a wind-loaded lattice pylon structure and has been found to produce small differences between the estimated strains and the strain gauge measurements, with lower estimated damage than that forecasted by traditional design rules.

### DAMPING ESTIMATION OF ENGINEERING STRUCTURES WITH AMBIENT RESPONSE MEASUREMENTS

Damping plays a key role in dynamic response prediction, vibration control. Following the brief description of ambient vibration testing and measurements, three nonparametric damping estimation approaches for engineering structures are introduced: (1) time domain approach using Data Correlation (DC); (2) time-frequency analysis via Wavelet Transform (WT), and (3) a spatial domain approach based on Frequency Domain Decomposition (FDD). The major focus of the damping estimation approaches presented is on their capability in dealing with on-site fullscale testing of engineering structures using ambient response measurement. Computer simulations based on ambient response measurements and modal identification of a 15-story office building and a transmission tower were conducted to evaluate their performances of different approaches in dealing with closely spaced modes and noisy data. Major challenges in damping estimation are also discussed.

#### 3 bullet points summary

-   The paper focuses on the role of damping in dynamic response prediction and vibration control
-   Three nonparametric damping estimation methods are introduced: Data Correlation (DC), Wavelet Transform (WT), and Frequency Domain Decomposition (FDD)
-   The methods are evaluated using computer simulations based on ambient response measurements of a 15-story office building and a transmission tower, and the results are discussed in terms of dealing with closely spaced modes and noisy data.


### ★[Foti 2011]Ambient vibration testing, dynamic identification and model updating of a historic tower.pdf

The results of an ambient-vibration based investigation conducted on a historical tower in Italy, to update the 3-D finite element model of the building are presented in this work. The main difficulties are related to the extreme in-homogeneity of the building and the presence of an elevator vain that occupies the posterior part of the tower, forcing to locate the accelerometers only on one fac-ade of the building. The assessment procedure include full-scale ambient vibration testing, modal identification from ambient vibration responses using three different identification methods, finite element modeling and dynamic-based identification of the uncertain structural parameters of the model. A very good match between theoretical and experimental modal parameters was reached and the model updating has been performed to identify some structural parameters.


#### 3 bullet points summary

1.  Ambient-vibration based investigation conducted on a historical tower in Italy
2.  The assessment procedure includes full-scale ambient vibration testing, modal identification and finite element modeling
3.  The results show good match between theoretical and experimental modal parameters and the model updating was performed to identify structural parameters.

## **Case Histroy**

### Case History Analysis of Bridge Failures due to Scour

Scour is a major cause for bridge failure. To understand the characteristics of bridge failures under scour conditions and provide useful information for scour countermeasure, this study reviewed and analyzed totally 36 historical cases of bridge failure due to scour, including their hydraulic, geotechnical, and structural conditions and failure modes. Based on the collected data, most of scour depths (i.e. up to 41%) ranged from 0.5 to 5 m; but, the maximum scour depth could be up to 15 m. Local scour was accounted for 64% bridge failures, followed by channel migration (14%), and contraction scour (5%). Possible bridge failure modes due to scour included vertical failure, lateral failure, torsional failure, and bridge deck failure. Approximately 70% of bridge failures were lateral and vertical. The findings from this study can be updated when more cases of bridge failure under scour conditions are collected and/or become available.

#### 3 bullet points summary

1.  This study reviewed and analyzed 36 historical cases of bridge failure caused by scour.
2.  The most common scour depths ranged from 0.5 to 5m and local scour accounted for 64% of the failures.
3.  The most common failure modes were lateral and vertical failure, accounting for 70% of the failures.

### ANALYSIS OF RECENT BRIDGE FAILURES IN THE UNITED STATES

Over 500 failures of bridge structures in the United States between 1989 and 2000 were studied. The age of the failed bridges ranged from 1 year (during construction) to 157 years, with an average of 52.5 years. The most frequent causes of bridge failures were attributed to floods and collisions. Flood and scour, with the major flood disaster in 1993, contributed to the frequency peak of bridge failures (almost 53% of all failures). Bridge overload and lateral impact forces from trucks, barges/ships, and trains constitute 20% of the total bridge failures. Other frequent principal causes are design, detailing, construction, material, and maintenance. Comparison made among three periods of similar studies (1977–1981, 1982–1988, and 1989–2000) revealed almost similar trends, with most failures occurring during the bridge’s service life. Also, human-induced external events occurred frequently in all three periods, but were most dominant in the first and third periods. 

#### 3 bullet points summary

1.  A study was conducted on over 500 bridge failures in the United States from 1989 to 2000.
2.  The most frequent causes of bridge failures were attributed to floods and collisions, followed by overload and lateral impact forces from trucks, barges/ships, and trains.
3.  The study revealed that human-induced external events frequently occurred in all three periods studied, but were most dominant in the first and third periods.


## Damage Detection

Statistical methods for damage detection applied to civil structures
Author links open overlay panelSzymon Gres a e, Martin Dalgaard Ulriksen b, Michael Döhler c, Rasmus Johan Johansen b, Palle Andersen d, Lars Damkilde b, Søren Andreas Nielsen e

Damage detection consists of monitoring the deviations of a current system from its reference state, characterized by some nominal property repeatable for every healthy state. Preferably, the damage detection is performed directly on vibration data, hereby avoiding modal identification of the structure. The practical aspect of using only the output measurements cause difficulties because of variations in ambient excitation due to variability in the environmental conditions, like sea, wind, and temperature. In this paper, a new Mahalanobis distance-based damage detection method is studied and compared to the well-known subspace-based damage detection algorithm in the context of two large case studies. Both methods are implemented in the modal analysis and structural health monitoring software ARTeMIS, in which the joint features of the methods are concluded in a control chart in an attempt to enhance the resolution of the damage detection. The damage indicators from both methods are evaluated based on the ambient vibration signals from numerical simulations on a novel offshore support structure and an experimental campaign with a full scale bridge. The results reveal that the performance of the two damage detection methods is similar, hereby implying merit of the new Mahalanobis distance-based approach, as it is less computational complex. The fusion of the damage indicators in the control chart provides the most accurate view on the progressively damaged systems.


A Comparison of Damage Detection Methods Applied to Civil Engineering Structures
Szymon Gres, Palle Andersen, Rasmus Johan Johansen, Martin Dalgaard Ulriksen & Lars Damkilde 


Facilitating detection of early-stage damage is crucial for in-time repairs and cost-optimized maintenance plans of civil engineering structures. Preferably, the damage detection is performed by use of output vibration data, hereby avoiding modal identification of the structure. Most of the work within the vibration-based damage detection research field assumes that the unmeasured excitation signal is time-invariant with a constant covariance, which is hardly achieved in practice. In this paper, we present a comparison of a new Mahalanobis distance-based damage detection method with the well-known subspace-based damage detection algorithm robust to changes in the excitation covariance. Both methods are implemented in the modal analysis and structural health monitoring software ARTeMIS, in which the joint features of the methods are concluded in a control chart in an attempt to enhance the damage detection resolution. The performances of the methods and their fusion are evaluated in the context of ambient vibration signals obtained from, respectively, numerical simulations on a simple chain-like system and a full-scale experimental example, namely, the Dogna Bridge. The results reveal that the performances of the two damage detection methods are quite similar, hereby evidencing the justification of the new Mahalanobis distance-based approach as it is less computational complex. The control chart presents a comprehensive overview of the progressively damaged structure.

A SUMMARY REVIEW OF VIBRATION-BASED DAMAGE IDENTIFICATION METHODS

This paper provides an overview of methods to detect, locate, and characterize damage in
structural and mechanical systems by examining changes in measured vibration response.
Research in vibration-based damage identification has been rapidly expanding over the last few
years. The basic idea behind this technology is that modal parameters (notably frequencies, mode
shapes, and modal damping) are functions of the physical properties of the structure (mass,
damping, and stiffness). Therefore, changes in the physical properties will cause detectable
changes in the modal properties. The motivation for the development of this technology is
presented. The methods are categorized according to various criteria such as the level of damage
detection provided, model-based vs. non-model-based methods and linear vs. nonlinear methods.
The methods are also described in general terms including difficulties associated with their
implementation and their fidelity. Past, current and future-planned applications of this technology
to actual engineering systems are summarized. The paper concludes with a discussion of critical
issues for future research in the area of vibration-based damage identification.

• Level 1: Determination that damage is present in the structure
• Level 2: Level 1 plus determination of the geometric location of the damage
• Level 3: Level 2 plus quantification of the severity of the damage
• Level 4: Level 3 plus prediction of the remaining service life of the structure

