---
title: "Reading Note"
author: "Kyeong Sun Kim"
date: "Some day in 2023"
jupyter: python3
---
## 사업계획서

### 고유진동수 영향인자 분석 (서울대 1-2차년도)

#### 수치모델링 기술개발

* 해상풍력 터빈시스템 자료조사
	+ 국내·외 해상풍력발전기 설계기준 및 시공사례 조사
	+ 해상풍력 터빈시스템 유한요소 해석 결과 조사 및 DB 구축
	+ 고유진동수 분석기법 및 세굴 안정성 평가법 조사


* 빔—흙 스프링 모델(Beam—spring model) 이상화 영향 평가
	+ 3차원 지반구조물-풍력타워구조 시스템과의 비교
	+ 지반강성 스프링의 삭제 방법과 강성감소 방법의 효과 비교
	+ 해상풍발전기 구조(블레이드, 터빈 등) 크기 및 위치 변화


* 수치해석모델의 고도화 및 가상 데이터 추출
	+ 평가모델개발을 위한 가상 데이터 추출
	+ 원심모형실험 계측자료를 이용한 수치해석모델 업데이팅


#### 원심모형실험

* 원심모형실험 상사법칙 및 스케일 지수 영향 분석
	+ 무차원 계수의 상관성 비교
	+ 1-g 모형실험을 통한 원심모형실험 상사비 영향 분석
	+ 원심모형실험 절차 및 회전(Spinning) 지속 시간 결정



* 실제 현장 풍력발전기를 모사한 구조물 제작
	+ 풍력발전기 제원(구조, 크기, 무게 등) 조사
	+ 풍력발전기의 구조적 특징이 반영된 구조물 제작



* 고유진동수 측정법 고도화 기술개발
	+ 고유진동수 측정을 위한 계측기 결정(가속도계, 변위계, 변형률계 등)
	+ 풍하중 모사를 위한 진동식 하중재하 장치 개발
	+ 실제 현장 세굴 모사를 위한 지반조성 장치 개발
	+ 동적 계측을 위해 적절한 데이터 로거 민감도 및 시계열 데이터의 타임 윈도우(time window) 범위


#### 지지력 및 고유진동수 변화 분석

* 지지력과 고유진동수의 상관관계 분석
	+ 극한 한계상태, 사용성 한계상태, 피로한계상태 등의 지반구조물의 지지력과 동적 특성치의 자기상관 및 상호상관 관계 분석
	+ 지지력과 지반구조시스템의 동적특성의 단순회귀모형을 통한 고유진동수 예측기법 개발



* 원심모형 실험결과를 통한 세굴 영향 검토
	+ 타워체 및 지지구조물의 물리적 특성치 (중량, 강성, 탄성계수 등)
	+ 지반 동적 특성치 (동적탄성계수, 동적토압 등)
	+ 기하학적 특성 (세장비, 폭-길이 비, 석션기초의 간격 등)
	+ 표면적 특성 (표면마찰계수, 흙의 점착력 등)



### 세굴안정성 평가 알고리즘 개발 (서울대-가천대)

#### 매개변수 연구를 통한 세굴영향 검토 (서울대)

* 지반—지지구조 인터페이스 결정(Soil Structure Interface; SSI)
	+ 지반—지지구조 인터페이스 마찰계수 영향 평가
	+ 초기응력조건(Initial Stress Condition)에 따른 영향 평가

* 유한요소 구조방정식 구성 성분의 분석
	+ 물질 구성모델(Material Constitutive Model) 분석
	+ 초기조건, 경계조건, 하중 조건 결정
	+ 수치해석 모델 변수 결정

* 타워 구조물과 지반의 불균질성을 고려한 변동성 확인
	+ 타워의 단면특성과 탄성계수의 불균질성의 영향 검토
	+ 흙의 깊이별 불균질성 계수를 통한 영향 분석


#### 세굴안정성 평가기술 개발 (서울대, 가천대)

* 진동 해석법과 다양한 모달 해석(Modal Analysis) 기법을 통한 고유진동수 분석
	+ 강제진동/상시진동시험을 통한 고유진동수 계측결과 비교분석
	+ 고유진동수 분석을 위한 ARTeMIS Modal Pro 소프트웨어의 적용성 검토
	+ 시간/주파수 영역 분석법 결과 비교분석
	+ 차수 해석, 시간 동기 평균화, 스펙트럼에 따른 결과분석
	+ 주파수—응답 함수, 고유 주파수, 감쇠비, 모드 형상 추정

* 통계 분석을 통한 시계열 데이터 전처리
	+ 앙상블 및 저장소를 이용한 데이터 모니터링 및 관리체계 개발
	+ 평균화 및 정규화를 통한 노이즈 필터 적용성 평가
	+ 기술적 통계량 (RMS 레벨, 왜곡비, 교차점 등)의 시계열 데이터의 특징 추출
	+ 노이즈와 변동성을 감소 시키기 위한 차원변형 및 시간 윈도우 분석
	+ 추계학(Stochastic) 및 확률론적인 기법의 적용성 평가

* 통계적 카이자승 가설검증(Chi-squared Hypothesis Test)을 이용한 세굴안정성 평가 기법 개발
	+ 고유진동수 변화와 상관계수가 높은 다양한 통계지수를 통한 한계치 설정
	+ 조건지표(Condition Indicator)를 통한 세굴안정성 지수 결정



#### 세굴 안정성 평가기술 검증 (서울대, 가천대)

*  수치모델의 정확도 평가

* 수치해석 결과 기반 머신러닝 모델 적용성 검토

* 다수의 시뮬레이션을 통한 고장검출 알고리즘 및 위험상태 검출 신뢰도 확인

* 이상치 탐색(Anomaly Detection Algorithm) 알고리즘의 정확도 평가




### 해상풍력 석션기초 세굴안정성 스마트 모니터링 기술개발 (가천대)

#### 세굴 감지를 위한 센서 및 해상풍력 터빈시스템 내 설치위치 결정

#### 세굴 안정성 최적 모니터링을 위한 계측기술 개발

#### 계측기반의 고유진동수 상시점검 및 평가체계 구축

#### 다양한 운영 시나리오를 고려한 세굴 안정성 평가지표 및 절차서 개발

