---
title: "Choices"
---


## Experimental Details

### Soil Choice
- Material model choice
	- Mohr-Coulomb Model
	- Hardening Mohr-Coulomb Model
	- Cyclic SANISAND Model
- Young's modulus and Poisson ratio
- Critical State Properties
- Nonlinear Parameters
- cohesion and tensile properties
- Cycllic strength parameters

### Structure Choice
- Rigid or Linear Elastic Material
- Young's modulus and Poisson ratio
- Fatigue properties (SN Curve)
- Hardness properties (BHN)


### SSI Choice
- Interface friction coefficient
	- Horizontal / Vertical
- Modulus of subgrade reaction of soil
	- Horizontal / Vertical / Rotational


### Loading Choice
- Actuators

Static vs Cyclic

- Vibrations

Forced vs Ambient
FFT vs FDD and EFDD

For experimental investigation, means and location of excitation, the density of the measurement point grid, the sampling rate and the length of time window must be optimized for good quality results.


| Method                                                                         | Advantages                                                      | Disadvantages                                               |
|--------------------------------------------------------------------------------|-----------------------------------------------------------------|-------------------------------------------------------------|
| Forced                                                                         | Provides "scaled" results                                       | Artificial vibration required                               |
| Excites all (broad) range of natural frequencies                               | First mode can be too low to be excited                         |
| Known force and mass, which allows FE updating                                 |                                                                 |
| Ambient                                                                        | No artificial excitation                                        | Lack of stationarity (not controllable). scatter may occur. |
| Better for low frequency (large and complex structures)                        | Not all natural frequency may be excited                        |
| Cheap (no shaker)                                                              | Non-linearity of structure itself (assumption of cross section) |
| Can be performed without embarrassing normal user (stopping traffic or humans) | Requires long cables                                            |
| Requires reference points >1 (3D or 1D sensors)                                |
| Time window must be selected > 1000~2000 times f_n                             |
| Requires manual techniques for FE updating                                     |


### Software Choice

- ABAQUS

	- UMAT implementation

- Plaxis 3D

- ARTeMIS Modal Pro

	- Operational Modal Analayis

	- Structural Health Monitoring

- SAP 2000
	- natural frequency for 3D structure on Winkler foundation



## Verification Plan

- Winkler model limitations

- Mass-spring model limitations

- Accelerometer locations

- Sensor Sensitivity and Capacity

-  Clear damage detection (condition chart)


## Deployment Process

- anomaly detection
- sesnsor deployment
- model validation
- threshold check
- damage detection

