project:
  type: book
  output-dir: docs
book:
  title: "ResearchNote"
  output-file: "docs"
  author: "Kyeong Sun Kim"
  date: "2023"
  favicon:favicon.png
  cover-image: cover.png
  twitter-card: false
  site-url: https://www.example.com
  repo-url: https://www.example.com
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook]
  search: true
  sidebar: 
    style: docked
    background: light
    
  - part: "Centrifuge Experiment"
  chapters: 
    - 1_1_background.qmd
    - 1_2_test_setup.qmd
    - 1_3_matl_prop.qmd
    - 1_4_scale_law.qmd
    - 1_5_analysis.qmd
    - 1_6_verification.qmd
    - 1_7_references.qmd
  - part: "Finite Element Analysis"
  chapters: 
    - 2_1_background.qmd
    - 2_2_numerical_setup.qmd
    - 2_3_matl_calib.qmd
    - 2_4_verification.qmd
    - 2_5_analysis.qmd
    - 2_6_validation.qmd
    - 2_7_references.qmd
  - part: "Ambient Vibration Test"
  chapters: 
    - 3_1_background.qmd
    - 3_2_test_setup.qmd
    - 3_3_operational_modal.qmd
    - 3_4_statistical.qmd
    - 3_5_damage_detection.qmd
    - 3_6_validation.qmd
    - 3_7_references.qmd
  Appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: right
    html-math-method: katex
    embed-resources: true
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    minimal: false
    
  pdf:
    documentclass: scrreprt
    keep-tex: true
    fontfamily: libertinus
    header-includes: |
      \usepackage{eplain}
      \usepackage{easy-todo}
      
  docx:
    reference-doc: custom.docx

quarto pandoc -o custom-reference.docx --print-default-data-file reference.docx

editor: visual

page-navigation: true
  
crossref:
  appendix-title: "App."
  appendix-delim: ":"

comments:
  hypothesis:
    theme: clean