project:
  type: book
  output-dir: docs
  
book:
  title: "ResearchNote"
  output-file: "docs"
  author: "Kyeong Sun Kim"
  date: "2023"
  site-url: https://kyeongsunkim.github.io
  repo-url: https://github.com/kyeongsunkim/kyeongsunkim.github.io.git
  search: true
  sidebar: 
    style: docked
    background: light
  chapters:  
    - index.qmd
    - part: "OMA"
      chapters:
        - 3_1_background.qmd
    - part: "Proposal"
      chapters:
        - 4_1_proposal.qmd
        - 4_3_literature.qmd

format:
  html:
    theme: cosmo
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: On this page
    toc-location: right
    html-math-method: katex
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    minimal: false

editor: visual

page-navigation: true
  
comments:
  hypothesis:
    theme: clean