project:
  type: book
  output-dir: docs
  
book:
  title: "ResearchNote"
  output-file: "docs"
  author: "Kyeong Sun Kim"
  date: "Some day in 2023"
  site-url: https://kyeongsunkim.github.io
  repo-url: https://github.com/kyeongsunkim/kyeongsunkim.github.io.git
  search: true
  sidebar: 
    style: docked
    background: light
  chapters:  
    - part: "My Research Note"
      chapters:
        - index.qmd
        - 2_TaskManager.qmd
        - 3_LiteratureReview.qmd
        - 4_AIWritingAssistant.qmd
        - 5_ReadingNote.qmd
        - 5_WritingNote.qmd        
        - 6_FormulaeNote.qmd
        - 7_IdeaNote.qmd
        - 8_VocabNote.qmd         
        - 9_CodeBlocks.qmd   
       
format:
  html:
    theme: cosmo
    code-copy: true
    code-fold: true
    toc: true
    toc-depth: 4
    toc-title: On this page
    toc-location: right
    html-math-method: katex
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    minimal: false

comments:
  hypothesis:
    theme: clean
    
filters:
  - collapse-callout
  - shinylive
  
collapse-callout:
  all: true
  
callout-appearance: simple
callout-icon: true
self-contained: false
editor: visual
page-navigation: true