---
title: "Front Matter"
author: "Kyeong Sun Kim"
date: "Some day in 2023"
jupyter: python3
---

# Task Manager

|      Task      |               Sub-task                |         Who         | Importance | Progress  |
|:-----------:|:--------------------:|:-----------:|:-----------:|:-----------:|
|   1,2 페이지   |           1,2,3차년도 예산            |       *성호*        |     ★★     |   ★★★★★   |
|                |      ~~**`연구 필요성 작성`**~~       |    ~~**경선**~~     |            | ~~★★★★★~~ |
|                |     ~~**`성과/활용방안 작성`**~~      |    ~~**경선**~~     |            | ~~★★★★★~~ |
|                |          서울대/가천대 도장           |       *성호*        |     ★      |   ☆☆☆☆☆   |
|                |          ~~접수 방법 문의~~           | ~~*성호*/**경선**~~ |   ~~★~~    | ~~★★★★★~~ |
|   2 관련현황   | **`국내외 교량대상 고유진동수 조사`** |      **경선**       |            |   ☆☆☆☆☆   |
|                | **`국내외 고유진동수 연구동향 조사`** |      **경선**       |            |   ☆☆☆☆☆   |
|                |       국내외 석션기초 시장 조사       |       가천대        |            |   ☆☆☆☆☆   |
|                |         국내외 모니터링 조사          |       가천대        |            |   ☆☆☆☆☆   |
|                |      국내외 현황/특허 문단 추가       |       *성호*        |            |   ☆☆☆☆☆   |
|  3 목표/내용   |      **`1,2,3차년도 내용 정리`**      |      **경선**       |    ★★★     |   ★★★☆☆   |
|   4 추진방법   |      **`원심모형실험 추진전략`**      |      **경선**       |    ★★★     |   ☆☆☆☆☆   |
|                |        **`수치해석 추진전략`**        |      **경선**       |    ★★★     |   ☆☆☆☆☆   |
|                |           모니터링 개발전략           |       가천대        |            |   ☆☆☆☆☆   |
|                |       4-2 팀 평성도 (기술내용)        |                     |            |   ☆☆☆☆☆   |
|                |           4-3 추진체계(표)            |                     |            |   ☆☆☆☆☆   |
|                |           4-4 추진일정(표)            |                     |            |   ☆☆☆☆☆   |
|    6 사업비    |  ~~인건비,직접비,간접비 예산 계산~~   |     ~~*성호*~~      |   ~~★★~~   | ~~★★★★★~~ |
|                |     전문가 활용 자문기관 추천받기     |                     |            |   ☆☆☆☆☆   |
|                |        국외 출장의 필요성 작성        |                     |            |   ☆☆☆☆☆   |
|                |       전문가 활용의 필요성 작성       |                     |            |   ☆☆☆☆☆   |
|                |        교육훈련의 필요성 작성         |                     |            |   ☆☆☆☆☆   |
| 별첨3 마일스톤 |           수행체계 및 계획            |                     |            |   ☆☆☆☆☆   |
|                |          점검 및 평가 계획표          |                     |            |   ☆☆☆☆☆   |
|                |                                       |                     |            |           |

-   A single degree-of-freedom system loaded by ambient white noise was investigated by statistical assessment of dynamic modal parameters such as natural frequency and damping factors of Offshore Wind Turbine(OWT).

-   The UNISON's U4 (4MW) OWT system of was simulated using advanced Finite Element modelling considering soil-structure interaction was validated and updated using a series of centrifuge experiments, which can account for the influence of soil's confining pressure and blade-rotor-nacelle assembly and tower's mass scale effects.

-   Using state-of-art statistical techniques such as correlation functions estimated by both Random Decrement Analysis (RDA) and Perturbation Wavelet Analysis (PWA) and Chi-squared Hypothesis Tests as a basis for system parameter identification, the OWT system was assessed by a threshold estimation procedure, developed with machine learning model fed with scour-damaged response data correlated with foundation's ULS, SLS, and FLS performances.

-   The model's accuracy was further enhanced by supervised learning from large amount of virtual data produced by the updated FEM model to be able to predict for a long term (20 years) Remaining Useful Life (RUL) or to classify Scour Health Index based on current system parameters.

-   The outcome of the study will lead to improved timing of maintenance and reduced offshore investigation and maintenance jobs, resulting in reduced risk of failure for the OWT. The system's dynamic property parameters can be monitored to ensure its safe operation.
